Repository mitodl/mitxpro, pull requests merged in 2019-12, with the labels that each got.

#1349 Added error reporting for coupon request spreadsheet
  mitxpro/settings.py
  sheets/api.py
  sheets/api_test.py
  sheets/conftest.py
  sheets/constants.py
  sheets/exceptions.py
  sheets/management/commands/process_coupon_request_row.py
  sheets/management/commands/process_coupon_requests.py
  sheets/tasks.py
  sheets/tasks_test.py
  sheets/utils.py
  sheets/utils_test.py
  sheets/views.py
Labels: Waiting on Author

#1355 Added model and task to manage coupon request webhook
  app.json
  mitxpro/admin.py
  mitxpro/models.py
  mitxpro/settings.py
  sheets/admin.py
  sheets/api.py
  sheets/configure_sheets_client.md
  sheets/factories.py
  sheets/management/commands/setup_request_sheet_file_watch.py
  sheets/migrations/0005_googlefilewatch.py
  sheets/models.py
  sheets/tasks.py
  sheets/tasks_test.py
  sheets/urls.py
  sheets/utils.py
  sheets/views.py
  sheets/views_test.py
Labels: Waiting on Author

#1360 Added spreadsheet sharing error handling
  sheets/api.py
  sheets/management/utils.py
Labels: Waiting on Author

#1361 restyle labels on dashboard
  static/js/components/Ribbon.js
  static/js/containers/pages/DashboardPage.js
  static/scss/dashboard.scss
Labels: Needs Review

#1362 #1345 Receipt Page
  ecommerce/constants.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/urls.py
  ecommerce/views.py
  mitxpro/urls.py
  static/images/mit-dark.png
  static/images/printer.png
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/ReceiptPage.js
  static/js/containers/pages/ReceiptPage_test.js
  static/js/flow/authTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/urls.js
  static/scss/layout.scss
  static/scss/receipt.scss
  users/serializers.py
Labels: Waiting on Author

#1366 Add product_id to hubspot line item
  hubspot/management/commands/configure_hubspot_bridge.py
  hubspot/serializers.py
  hubspot/serializers_test.py
Labels: Waiting on Author

#1364 Send cookie to hubspot when a user creates a new account
  app.json
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#1314 #1246 sync course runs from edx
  app.json
  courses/management/commands/sync_courseruns.py
  courses/tasks.py
  courses/utils.py
  courses/utils_test.py
  courseware/api.py
  mitxpro/settings.py
Labels: Waiting on Author

#1369 Fixed file watch bug and added management command options
  sheets/api.py
  sheets/management/commands/setup_request_sheet_file_watch.py
  sheets/tasks.py
Labels: Waiting on Author

#1371 Set coupon assignment sheet status when coupon is redeemed
  ecommerce/api.py
  ecommerce/api_test.py
  sheets/api.py
  sheets/api_test.py
  sheets/constants.py
  sheets/tasks.py
  sheets/utils.py
Labels: Waiting on Author

#1367 MIT xPRO 1346 - Add link to receipt(s) to dashboard
  app.json
  courses/serializers.py
  courses/serializers_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/settings.py
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/containers/pages/ReceiptPage.js
  static/js/containers/pages/ReceiptPage_test.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/queries/users.js
Labels: Needs Review

#1377 add search for courserungrade in admin
  courses/admin.py
Labels: Waiting on Author

#1383 Changed assignment sheet title
  sheets/api.py
  sheets/constants.py
  sheets/management/commands/create_coupon_assignment_sheet.py
  sheets/utils.py
Labels: Waiting on Author

#1356 list unredeemed enrollments on dashboard
  app.json
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/models.py
  ecommerce/models_test.py
  mitxpro/settings.py
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/flow/ecommerceTypes.js
  static/scss/dashboard.scss
  users/serializers.py
  users/views_test.py
Labels: Waiting on Author

#1374 asadiqbal08/mit-1344 Email receipt to the user
  ecommerce/api.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/views.py
  mail/constants.py
  mail/templates/email_base.html
  mail/templates/product_order_receipt/body.html
  mail/templates/product_order_receipt/subject.txt
Labels: Waiting on Author

#1382 Optimized coupon assignment sheets processing to ignore unchanged sheets
  ecommerce/migrations/0023_bulkcouponassignment_assignment_sheet_last_modified.py
  ecommerce/models.py
  sheets/api.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/tasks.py
  sheets/utils.py
Labels: Waiting on Author

#1396 Fixed bug with updating coupon assignment rows upon enrollment
  sheets/tasks.py
Labels: Needs Review

#1376 Prevented repeated processing of failed coupon request rows
  mitxpro/settings.py
  sheets/admin.py
  sheets/api.py
  sheets/api_test.py
  sheets/conftest.py
  sheets/exceptions.py
  sheets/migrations/0006_coupon_gen_request_err_handling_fields.py
  sheets/migrations/0007_fill_in_gen_request_date_completed.py
  sheets/migrations/0008_remove_coupongenerationrequest_completed.py
  sheets/models.py
  sheets/tasks_test.py
  sheets/utils.py
  sheets/utils_test.py
Labels: Waiting on Author

#1397 Forced spreadsheet file watch renewal in running job
  sheets/tasks.py
Labels: Waiting on Author

#1401 Fixed bug with updating coupon assignment rows upon enrollment
  sheets/tasks.py
Labels: Waiting on Author

#1387 Modified request sheet handling to allow for requester email column
  mitxpro/settings.py
  sheets/api.py
  sheets/utils.py
Labels: Waiting on Author

#1402 Changed coupon request handling to create unrecognized companies
  sheets/api.py
  sheets/api_test.py
Labels: Waiting on Author

#1411 asadiqbal08/Display correct course name over receipt email
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/templates/product_order_receipt/body.html
Labels: Needs Review

#1291 optimize repetitive looping on course catalog page
  courses/models.py
  courses/models_test.py
Labels: Waiting on Author

#1407 Disable server-side cursors by default to avoid invalid cursor errors
  app.json
  mitxpro/settings.py
  mitxpro/settings_test.py
Labels: Waiting on Author

#1423 Added setting for overriding host used in SSL redirect
  app.json
  mitxpro/settings.py
Labels: DevOps, Waiting on Author

#1414 change value of constant
  b2b_ecommerce/constants.py
Labels: Needs Review

#1409 Fixed sheets error handling & management command bugs
  mitxpro/settings.py
  sheets/api.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_requests.py
  sheets/utils.py
Labels: Waiting on Author

#1415 MIT xPRO - 1386 Checkout: Display success message when coupon is successfully
  static/js/components/forms/CheckoutForm.js
  static/js/lib/form.js
  static/scss/checkout.scss
  static/scss/variables.scss
Labels: Waiting on Author

#1405 #1313 update sync_grades_and_certificates command msg
  courses/management/commands/sync_grades_and_certificates.py
Labels: Needs Review

#1426 #1395 Delay automated certificate creation by a number of hours
  app.json
  courses/tasks.py
  mitxpro/settings.py
Labels: Needs Review

#1431 MIT xPRO - 1389 add flag for hide/show product in bulk seat page
  ecommerce/api_test.py
  ecommerce/migrations/0024_add_product_visible_in_bulk_form_field.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1433 Added validation and reporting for emails in coupon assignment sheets
  mail/api.py
  mail/exceptions.py
  sheets/api.py
  sheets/constants.py
  sheets/tasks.py
  sheets/utils.py
Labels: Waiting on Author

#1441 #1438 display dollars and cents in both email and receipt page
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
Labels: Waiting on Author

#1445 update the serialize-javascript
  package.json
  yarn.lock
Labels: Waiting on Author

#1442 asadiqbal08/mitxpro-1391 Included user's street address
  authentication/pipeline/compliance.py
  users/models.py
Labels: Waiting on Author

#1449 Updated the version of handlebars
  package.json
  yarn.lock
Labels: Needs Review

#1446 Added warning for 'automatic' option in coupon creation form
  static/js/components/forms/CouponForm.js
  static/scss/ecommerce-admin.scss
Labels: Waiting on Author

#1451 Create a ProgramEnrollment along with ProgramCertificate
  courses/serializers.py
  courses/utils.py
Labels: Needs Review
