Repository mitodl/mitxpro, pull requests merged in 2019-07, with the labels that each got.

#700 Added 'create account' link to sign in page
  static/js/components/forms/EmailForm.js
  static/js/components/forms/EmailForm_test.js
  static/js/containers/pages/login/LoginEmailPage.js
Labels: Merge after freeze, Waiting on Author

#713 Reordered CMS model definitions
  cms/models.py
Labels: Waiting on Author

#729 #726 Remove blog link from footer
  mitxpro/templates/footer.html
Labels: Waiting on Author

#724 Use program.title and run.title instead of product.description
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  static/js/components/forms/CheckoutForm.js
  static/js/components/forms/CheckoutForm_test.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#672 Added enrollment audit admin classes
  courses/admin.py
Labels: Waiting on Author

#734 Remove the old PR template that is hiding the new one
  .github/pull_request_template.md
Labels: Waiting on Author

#701 Use site wide notifications for dashboard
  static/js/components/NotificationContainer.js
  static/js/components/NotificationContainer_test.js
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/reducers/notifications.js
  static/scss/notification.scss
Labels: Waiting on Author

#730 autoComplete attributes for form fields (Chrome)
  static/js/components/forms/EmailForm.js
  static/js/components/forms/EmailForm_test.js
  static/js/components/forms/ProfileFormFields.js
  static/js/components/forms/RegisterDetailsForm_test.js
  static/js/components/forms/RegisterEmailForm.js
  static/js/components/forms/RegisterEmailForm_test.js
Labels: Waiting on Author

#732 #715 Make cms subheads optional
  cms/migrations/0036_make_subhead_optional.py
  cms/models.py
  cms/templates/partials/course-carousel.html
  cms/templates/partials/faculty-carousel.html
  cms/templates/partials/learning-outcomes.html
  cms/templates/partials/testimonial-carousel.html
  mitxpro/templates/resource_template.html
Labels: Waiting on Author

#748 #738 Remove course position label from product page
  cms/templates/partials/hero.html
Labels: Needs Review

#749 #739 Remove contractions from subnav
  cms/templates/partials/subnav.html
Labels: Needs Review

#676 Save order on enrollment objects
  courses/factories.py
  courses/management/commands/defer_enrollment.py
  courses/management/commands/transfer_enrollment.py
  courses/migrations/0016_enrollment_order.py
  courses/models.py
  courses/views_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/views_test.py
  static/js/factories/course.js
Labels: Waiting on Author

#750 #740 Product Page: Add commas to prices tile
  cms/templates/partials/metadata-tiles.html
Labels: Waiting on Author

#745 Updating wording on the verification email
  mail/templates/verification/body.html
Labels: Waiting on Author

#728 Fixed catalog login/signup urls
  cms/models.py
  cms/templates/partials/hero.html
  static/js/containers/pages/register/RegisterExtraDetailsPage.js
  static/js/lib/selectors.js
  static/js/lib/selectors_test.js
Labels: Waiting on Author

#725 Disable submit button while processing
  static/js/components/forms/CheckoutForm.js
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/lib/queries/ecommerce.js
Labels: Waiting on Author

#691 Switch hardcoded url to reverse url
  voucher/views.py
  voucher/views_test.py
Labels: Waiting on Author

#692 Add readable_id to ProductVersion
  courses/models.py
  ecommerce/admin.py
  ecommerce/migrations/0014_productversion_text_id.py
  ecommerce/models.py
  ecommerce/models_test.py
Labels: Waiting on Author

#747 Added catalog link to empty dashboard
  static/js/containers/pages/DashboardPage.js
  static/scss/common.scss
  static/scss/dashboard.scss
Labels: Waiting on Author

#642 redirect the wagtail login to the site login
  mitxpro/urls.py
  mitxpro/views.py
  mitxpro/views_test.py
Labels: Waiting on Author

#696 Fixed and refactored enrollment commands
  courses/management/commands/defer_enrollment.py
  courses/management/commands/refund_enrollment.py
  courses/management/commands/transfer_enrollment.py
  courses/management/utils.py
  courses/models.py
  courses/models_test.py
  mitxpro/utils.py
  mitxpro/utils_test.py
Labels: Blocked, Waiting on Author

#706 restyling catalog page to allow featured course
  cms/migrations/0037_featured_product.py
  cms/models.py
  cms/models_test.py
  cms/templates/catalog_page.html
  cms/templates/partials/featured_card.html
  static/scss/catalog/body.scss
  static/scss/catalog/tabs.scss
  static/scss/variables.scss
Labels: Needs Review

#766 Do not include unused_coupons field when syncing contacts to hubspot
  hubspot/api.py
  hubspot/api_test.py
Labels: Needs Review

#768 fix hardcoded product page url
  cms/templates/partials/featured_card.html
Labels: Needs Review

#737 Coupon form improvements
  static/js/components/forms/CouponForm.js
  static/js/components/forms/CouponForm_test.js
Labels: Waiting on Author

#760 Add notification when user verifies their email
  static/js/containers/pages/register/RegisterConfirmPage.js
  static/js/containers/pages/register/RegisterConfirmPage_test.js
Labels: Waiting on Author

#771 Upgrade sentry for Python and JS
  mitxpro/celery.py
  mitxpro/settings.py
  mitxpro/templates/base.html
  mitxpro/utils.py
  mitxpro/utils_test.py
  mitxpro/views.py
  mitxpro/views_test.py
  mitxpro/wsgi.py
  package.json
  requirements.in
  requirements.txt
  static/js/entry/root.js
  yarn.lock
Labels: Waiting on Author

#787 Tasawer/fix account creation for Canadian users
  authentication/serializers.py
  static/js/containers/pages/register/RegisterEmailPage.js
  users/serializers.py
  users/serializers_test.py
Labels: Needs Review

#798 fix regex for false positive, add test for invalid codes
  users/serializers.py
  users/serializers_test.py
Labels: Needs Review

#751 #742 Learning Outcomes subhead convert to richtext
  cms/migrations/0038_learning_outcomes_subhead_richtext.py
  cms/models.py
  cms/models_test.py
  cms/templates/partials/learning-outcomes.html
Labels: Waiting on Author

#752 #743 Product page catalog details
  cms/migrations/0039_product_page_catalog_details.py
  cms/models.py
  cms/models_test.py
  cms/templates/partials/catalog-card.html
Labels: Waiting on Author

#799 styling header links for mobile view
  static/js/components/TopAppBar.js
  static/scss/top-app-bar.scss
  static/scss/user-menu.scss
Labels: Waiting on Author

#801 #800 Update Readme regarding index page setup management command
  README.md
Labels: Needs Review

#773 Fix django admin search for CoursewareUser
  courseware/admin.py
Labels: Waiting on Author

#779 new background for faculty section
  static/images/faculty-bg.jpg
Labels: Needs Review

#781 Coerce fields to and from empty strings to fix React uncontrolled warnings
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EditProfileForm_test.js
  static/js/containers/pages/profile/EditProfilePage.js
  static/js/containers/pages/profile/EditProfilePage_test.js
Labels: Waiting on Author

#797 Change validation error message to Enrollment / Promotional Code
  ecommerce/serializers.py
  ecommerce/views_test.py
Labels: Waiting on Author

#757 Update styling of enrolled button and add a check mark
  cms/templates/partials/hero.html
  courses/views_test.py
  mitxpro/templates/base.html
  static/images/expand_less.svg
  static/images/expand_more.svg
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/scss/dashboard.scss
  static/scss/detail/header.scss
Labels: Waiting on Author

#806 Added config to avoid OSERRORs from uwsgi
  config/nginx.conf.erb
Labels: Waiting on Author

#802 minor scss fixes
  static/scss/detail/companies-trust.scss
  static/scss/slick.scss
Labels: Waiting on Author

#360 Automate environment variables
  app.base.json
  app.json
  docker-compose.travis.yml
  docker-compose.yml
  mitxpro/apps.py
  mitxpro/envs.py
  mitxpro/envs_test.py
  mitxpro/management/__init__.py
  mitxpro/management/commands/__init__.py
  mitxpro/management/commands/generate_app_json.py
  mitxpro/settings.py
  mitxpro/settings_test.py
Labels: Waiting on Author

#816 fix color of navigational arrows
  static/scss/slick.scss
Labels: Needs Review

#807 Added command to decrypt exports inquiry
  authentication/pipeline/user.py
  compliance/api.py
  compliance/api_test.py
  compliance/management/commands/decrypt_exports_inquiry.py
Labels: Waiting on Author

#813 Vouchers for django admin
  voucher/admin.py
Labels: Waiting on Author

#731 Fixed seed data bugs, added products, added deletion command
  cms/utils.py
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/management/commands/delete_seed_data.py
  localdev/seed/management/commands/seed_data.py
  localdev/seed/resources/seed_data.json
  mitxpro/utils.py
  mitxpro/utils_test.py
Labels: Waiting on Author

#803 #776 Allow Mixed Case Section Heads and Subheads
  cms/templates/partials/course-carousel.html
  cms/templates/partials/faculty-carousel.html
  cms/templates/partials/for-teams.html
  cms/templates/partials/learning-techniques.html
  cms/templates/partials/target-audience.html
  cms/templates/partials/text-section.html
  cms/templates/partials/text-video-section.html
  static/scss/detail/companies-trust.scss
  static/scss/detail/faculty.scss
  static/scss/detail/for-teams.scss
  static/scss/detail/learning-techniques.scss
  static/scss/detail/testimonial-carousel.scss
Labels: Waiting on Author

#804 #792 Featured Product Card Thumbnail Fix
  cms/templates/partials/catalog-card.html
  cms/templates/partials/featured_card.html
Labels: Waiting on Author

#814 Find old vouchers, ensure unique pdf names, add more error logging
  voucher/conftest.py
  voucher/migrations/0003_pdf_filename.py
  voucher/models.py
  voucher/utils.py
  voucher/utils_test.py
  voucher/views.py
  voucher/views_test.py
Labels: Needs Review

#826 Fix typo with command arg
  compliance/management/commands/decrypt_exports_inquiry.py
Labels: Waiting on Author

#785 Upgrade Django to 2.2, wagtail to 2.5.1
  cms/models.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#825 asadiqbal08/mitx-pro363 Used ImageChooserPanel
  cms/models.py
Labels: Waiting on Author

#836 fix comparison error when there is not start_data for course run
  courses/models.py
  courses/models_test.py
Labels: Needs Review

#794 Fixed enrollment commands - set order status, changed output
  courses/management/commands/defer_enrollment.py
  courses/management/commands/refund_enrollment.py
  courses/management/commands/transfer_enrollment.py
  courses/management/utils.py
Labels: Waiting on Author

#822 Change URLs for vouchers to /boeing
  mitxpro/urls.py
  voucher/views_test.py
Labels: Waiting on Author

#828 Change voucher pages style
  static/scss/layout.scss
  static/scss/variables.scss
  static/scss/voucher.scss
  voucher/templates/enroll.html
  voucher/templates/redeemed.html
  voucher/templates/resubmit.html
  voucher/templates/upload.html
Labels: Work in Progress

#829 Update some JS dependencies
  package.json
  static/js/babelhook.js
  yarn.lock
Labels: Waiting on Author

#862 dont load hero banner video on mobile devices
  cms/templates/partials/hero.html
  mitxpro/settings.py
  requirements.in
  requirements.txt
Labels: Needs Review

#840 asadiqbal08/mitxpro-709 Wrong price for program
  cms/templates/partials/catalog-card.html
  cms/templates/partials/featured_card.html
  cms/templates/partials/metadata-tiles.html
Labels: Needs Review

#845 Upgrade some Python dependencies
  requirements.in
  requirements.txt
Labels: Waiting on Author

#863 add heading field in who should enroll section
  cms/migrations/0040_whoshouldenrollpage_heading.py
  cms/models.py
  cms/models_test.py
  cms/templates/partials/target-audience.html
Labels: Waiting on Author

#856 Use next_run_id for a default for the checkout page course run selection
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
Labels: Waiting on Author

#852 Remove pep8
  pytest.ini
  test_requirements.txt
Labels: Waiting on Author

#871 display message when account already exists
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/containers/pages/register/RegisterEmailPage_test.js
Labels: Waiting on Author

#887 #885 Use catalog_details for featured product card
  cms/templates/partials/featured_card.html
Labels: Needs Review

#795 Add protection rules for ProductVersion, CouponVersion, CouponPaymentVersion
  ecommerce/api_test.py
  ecommerce/migrations/0015_db_protect.py
  ecommerce/models_test.py
  ecommerce/test_utils.py
  ecommerce/utils.py
  ecommerce/views_test.py
  localdev/seed/api_test.py
Labels: Needs Review

#891 Move hubspot contact sync task out of atomic transactions
  users/serializers.py
Labels: Needs Review

#895 Changed refund command to properly create order audit record
  courses/management/commands/refund_enrollment.py
Labels: Waiting on Author

#830 Django admin for version tables
  ecommerce/admin.py
  static/css/django-admin-version.css
Labels: Needs Review

#861 Update audit table serialization for program and course run enrollments
  courses/models.py
  courses/models_test.py
  mitxpro/test_utils.py
Labels: Waiting on Author

#897 Fix styling on account exists message
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/containers/pages/register/RegisterEmailPage_test.js
Labels: Needs Review

#898 Add staff payment_type to CouponPaymentVersion
  ecommerce/migrations/0016_payment_type_choices.py
  ecommerce/models.py
  static/js/components/forms/CouponForm.js
  static/js/components/forms/CouponForm_test.js
Labels: Waiting on Author

#910 #908 Wagtail admin generated URLs for child pages
  cms/models.py
  cms/models_test.py
Labels: Needs Review

#912 Added tagging for sentry errors to review apps
  app.json
  mitxpro/settings.py
Labels: Waiting on Author

#888 #882 display more dates on program page
  cms/templates/partials/metadata-tiles.html
  courses/models.py
  courses/models_test.py
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
Labels: Needs Review

#922 Update JS to fix caniuse-lite warning
  package.json
  yarn.lock
Labels: Waiting on Author

#920 #914 Inactive products should not show on catalog
  cms/models.py
  cms/views_test.py
Labels: Waiting on Author

#886 #783 React should scroll to top on page load
  static/js/Router.js
  static/js/components/ScrollToTop.js
Labels: Waiting on Author

#896 Add more information to OrderAudit
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author
