Repository mitodl/mitxpro, pull requests merged in 2019-05, with the labels that each got.

#170 asadiqbal08/mitxpro 142 - Product Page: What You'll Learn
  cms/factories.py
  cms/migrations/0008_learningoutcomespage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/course_detail.html
  static/images/dotted-bg.png
  static/scss/detail/common.scss
  static/scss/detail/learning-outcomes.scss
  static/scss/detail/tiles.scss
  static/scss/layout.scss
  static/scss/variables.scss
Labels: Waiting on Author

#209 Updated travis script section ANSI colors
  travis/js_tests.sh
  travis/python_tests.sh
Labels: Waiting on Author

#218 update docker compose for local debugging
  docker-compose.yml
Labels: Waiting on Author

#180 Zagaran/boeing voucher
  Dockerfile
  app.json
  mitxpro/settings.py
  requirements.in
  requirements.txt
  voucher/.test/domestic_voucher.pdf
  voucher/.test/domestic_voucher_test_credits.pdf
  voucher/.test/international_voucher.pdf
  voucher/__init__.py
  voucher/admin.py
  voucher/apps.py
  voucher/migrations/__init__.py
  voucher/models.py
  voucher/utils.py
  voucher/utils_test.py
  voucher/views.py
Labels: Waiting on Author

#219 Move deps into apt.txt so heroku installs them too
  Aptfile
  Dockerfile
  app.json
  apt.txt
  mitxpro/settings.py
  requirements.in
  runtime.txt
Labels: Needs Review

#200 asadiqbal08/mitxpro-144 Product Page: How you will learn
  cms/blocks.py
  cms/factories.py
  cms/migrations/0009_learningtechniquespage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/course_app_base.html
  courses/templates/course_detail.html
  static/images/bg-access.png
  static/scss/detail/common.scss
  static/scss/detail/learning-outcomes.scss
  static/scss/detail/learning-techniques.scss
  static/scss/layout.scss
  static/scss/variables.scss
Labels: Needs Review

#189 For Teams Section (#148)
  cms/factories.py
  cms/migrations/0011_for_teams_subpage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/course_detail.html
  mitxpro/templates/base.html
  static/images/default-for-teams-image.jpg
  static/images/for-teams-bg.png
  static/scss/detail/for-teams.scss
  static/scss/layout.scss
Labels: Needs Review

#179 #143 Product Page: Who Should Enroll
  cms/factories.py
  cms/migrations/0012_who_should_enroll_subpage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/_faqs.html
  courses/templates/course_detail.html
  static/images/who-should-enroll-bg.png
  static/scss/detail/common.scss
  static/scss/detail/learning-outcomes.scss
  static/scss/detail/tiles.scss
  static/scss/detail/who-should-enroll.scss
  static/scss/layout.scss
  static/scss/variables.scss
Labels: Needs Review

#211 Registration detail form - Step 1
  authentication/exceptions.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/views_test.py
  static/js/components/forms/FormError.js
  static/js/components/forms/RegisterDetailsForm.js
  static/js/components/forms/RegisterDetailsForm_test.js
  static/js/containers/pages/register/RegisterDetailsPage.js
  static/js/containers/pages/register/RegisterPages.js
  static/js/flow/authTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/queries/users.js
  static/scss/auth.scss
  static/scss/common.scss
  static/scss/layout.scss
  static/scss/variables.scss
  users/admin.py
  users/migrations/0004_user_legaladdress.py
  users/models.py
  users/serializers.py
  users/serializers_test.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Waiting on Author

#186 Course run selection UI, various backend changes
  courses/serializers.py
  courses/serializers_test.py
  courses/urls.py
  courses/views.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/factories.py
  ecommerce/migrations/0009_help_text.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/factories/course.js
  static/js/factories/ecommerce.js
  static/js/flow/courseTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/checkout.scss
Labels: Needs Review

#234 Redirect users to /dashboard after CyberSource checkout
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#235 Added user dashboard
  courses/api.py
  courses/api_test.py
  courses/constants.py
  courses/constants_test.py
  courses/factories.py
  courses/migrations/0007_add_enrollment_models.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/urls.py
  courses/views.py
  courses/views_test.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0010_remove_ecommerce_course_run_enrollment.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views_test.py
  localdev/seed/resources/course_seed_data.json
  mitxpro/urls.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  package.json
  static/images/expand_less.svg
  static/images/expand_more.svg
  static/js/components/PrivateRoute.js
  static/js/components/PrivateRoute_test.js
  static/js/components/Ribbon.js
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/js/containers/App.js
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/containers/pages/HomePage.js
  static/js/containers/pages/HomePage_test.js
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
  static/js/lib/courses.js
  static/js/lib/courses_test.js
  static/js/lib/queries/ecommerceAdmin.js
  static/js/lib/queries/enrollment.js
  static/js/lib/queries/enrollment_test.js
  static/js/lib/queries/index.js
  static/js/lib/queries/util.js
  static/js/lib/test_utils.js
  static/js/lib/urls.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/common.scss
  static/scss/dashboard.scss
  static/scss/layout.scss
  static/scss/top-app-bar.scss
  static/scss/variables.scss
  yarn.lock
Labels: Waiting on Author

#262 Tasawer/fix build
  test_requirements.txt
Labels: Waiting on Author

#229 asadiqbal08/mitxpro-214+185 Catalog Changes.
  courses/templates/catalog.html
  courses/templates/catalog_card.html
  courses/templates/contact_us.html
  courses/templates/footer.html
  mitxpro/templates/base.html
  mitxpro/templates/footer.html
  mitxpro/urls.py
  mitxpro/urls_test.py
  static/images/bg-contact.jpg
  static/images/header-banner.jpg
  static/images/mit.png
  static/js/catalog.js
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/js/lib/urls.js
  static/scss/catalog/banner.scss
  static/scss/catalog/body.scss
  static/scss/catalog/keep-me-posted.scss
  static/scss/catalog/tabs.scss
  static/scss/footer.scss
  static/scss/layout.scss
  static/scss/top-app-bar.scss
  static/scss/variables.scss
Labels: Needs Review

#237 #145 Product Page: Learners Carousel
  cms/blocks.py
  cms/factories.py
  cms/migrations/0015_user_testimonials_subpage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/course_detail.html
  courses/templates/partials/metadata-tiles.html
  courses/templates/partials/testimonial-carousel.html
  static/fonts/icomoon.eot
  static/fonts/icomoon.svg
  static/fonts/icomoon.ttf
  static/fonts/icomoon.woff
  static/images/testimonial-carousel-bg.jpg
  static/js/course_detail.js
  static/scss/detail/for-teams.scss
  static/scss/detail/testimonial-carousel.scss
  static/scss/icomoon.scss
  static/scss/layout.scss
  static/scss/slick.scss
Labels: Needs Review

#221 #146 Product Page: Faculty Carousel
  cms/blocks.py
  cms/factories.py
  cms/migrations/0016_faculty_members_subpage.py
  cms/models.py
  courses/models.py
  courses/models_test.py
  courses/templates/course_detail.html
  courses/templates/partials/faculty-carousel.html
  static/images/faculty-bg.jpg
  static/js/course_detail.js
  static/scss/detail/faculty.scss
  static/scss/layout.scss
  static/scss/slick.scss
Labels: Needs Review

#280 Don't check CSRF token for index pages
  mitxpro/views.py
  mitxpro/views_test.py
Labels: Waiting on Author

#290 Renamed BulkEnrollmentDelivery to ProductCouponAssignment
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/mail_api.py
  ecommerce/migrations/0011_rename_bulk_enrollment_delivery.py
  ecommerce/models.py
Labels: Waiting on Author

#265 Styling for checkout page
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/lib/ecommerce.js
  static/js/lib/ecommerce_test.js
  static/scss/checkout.scss
Labels: Needs Review

#192 #161 Product Page: More Dates
  courses/models.py
  courses/models_test.py
  courses/templates/catalog.html
  courses/templates/course_app_base.html
  courses/templates/partials/metadata-tiles.html
  mitxpro/templates/base.html
  static/js/catalog.js
  static/js/course_detail.js
  static/scss/detail/tiles.scss
Labels: Needs Review

#243 Additional kwargs, better efficiency for get_valid_coupon_versions query
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
Labels: Waiting on Author

#285 Misc. improvements - dashboard style, root route, enrollment admin
  courses/admin.py
  courses/views_test.py
  mitxpro/urls.py
  mitxpro/urls_test.py
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/scss/dashboard.scss
Labels: Waiting on Author

#297 #294 Fix Header Navbar Structure
  static/js/components/TopAppBar.js
  static/scss/top-app-bar.scss
Labels: Needs Review

#292 Updated notebook Dockerfile to be based off correct image
  Dockerfile-nb
Labels: Waiting on Author

#287 Track enrollment company
  courses/factories.py
  courses/migrations/0008_enrollment_company.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/serializers.py
  ecommerce/views_test.py
Labels: Waiting on Author

#303 Fixed dashboard styling again
  static/js/containers/pages/DashboardPage.js
  static/scss/dashboard.scss
Labels: Waiting on Author

#293 #193 Product Page: Subnav
  courses/templates/course_app_base.html
  courses/templates/course_detail.html
  courses/templates/partials/course-carousel.html
  courses/templates/partials/faculty-carousel.html
  courses/templates/partials/faqs.html
  courses/templates/partials/for-teams.html
  courses/templates/partials/learning-outcomes.html
  courses/templates/partials/learning-techniques.html
  courses/templates/partials/subnav.html
  courses/templates/partials/target-audience.html
  courses/templates/partials/testimonial-carousel.html
  static/js/course_detail.js
  static/scss/detail/subnav.scss
  static/scss/layout.scss
Labels: Needs Review

#308 Added recaptcha to register page
  mitxpro/views.py
  mitxpro/views_test.py
  package.json
  static/js/components/ScaledRecaptcha.js
  static/js/components/forms/RegisterEmailForm.js
  static/js/components/forms/RegisterEmailForm_test.js
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/flow/declarations.js
  static/js/lib/queries/auth.js
  yarn.lock
Labels: Waiting on Author

#259 Added API calls to validate user for export compliance
  app.json
  authentication/exceptions.py
  authentication/pipeline/compliance.py
  authentication/pipeline/compliance_test.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/utils.py
  authentication/views_test.py
  compliance/__init__.py
  compliance/api.py
  compliance/api_test.py
  compliance/apps.py
  compliance/constants.py
  compliance/factories.py
  compliance/migrations/0001_add_export_inquiry_log.py
  compliance/migrations/__init__.py
  compliance/models.py
  compliance/test_data/cybersource/100_success.xml
  compliance/test_data/cybersource/100_success_match.xml
  compliance/test_data/cybersource/151_timeout.xml
  compliance/test_data/cybersource/700_reject.xml
  compliance/test_data/cybersource/978_unknown.xml
  compliance/test_data/cybersource/CyberSourceTransaction_1.154.wsdl
  compliance/test_data/cybersource/CyberSourceTransaction_1.154.xsd
  compliance/test_utils.py
  conftest.py
  fixtures/common.py
  fixtures/cybersource.py
  mitxpro/settings.py
  mitxpro/views.py
  mitxpro/views_test.py
  pytest.ini
  requirements.in
  requirements.txt
  static/js/containers/pages/register/RegisterDetailsPage.js
  static/js/flow/authTypes.js
  static/js/flow/declarations.js
  static/js/lib/auth.js
  test_requirements.txt
  users/factories.py
  users/migrations/0006_user_is_active_false.py
  users/models.py
  users/models_test.py
Labels: Needs Review

#296 Fix coupon apply button bug
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
Labels: Needs Review

#283 Use query parameters when loading checkout page
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/lib/form.js
  static/js/lib/form_test.js
Labels: Needs Review

#330 Move Header Bundle back to Original Location
  courses/templates/course_app_base.html
  mitxpro/templates/base.html
  mitxpro/templates/resource_template.html
  mitxpro/views_test.py
Labels: Needs Review

#319 Jk/hubspot ecommerce sync
  ecommerce/hubspot_api.py
  ecommerce/hubspot_api_test.py
  ecommerce/management/commands/configure_hubspot_bridge.py
  ecommerce/tasks.py
  ecommerce/tasks_test.py
  mitxpro/settings.py
  users/serializers.py
  users/views_test.py
Labels: Needs Review

#309 Tasawer/242/site notifications
  cms/factories.py
  cms/migrations/0018_sitenotification.py
  cms/models.py
  cms/models_test.py
  mitxpro/templates/base.html
  mitxpro/templates/partials/notifications.html
  mitxpro/templatetags/render_notification.py
  static/js/notifications.js
  static/scss/layout.scss
  static/scss/notification.scss
Labels: Waiting on Author

#332 Fixed encrypted response getting ascii-escaped
  compliance/api.py
  compliance/api_test.py
Labels: Waiting on Author

#336 Enroll/View Dashboard button
  courses/models.py
  courses/models_test.py
  courses/templates/partials/hero.html
  courses/views.py
  courses/views_test.py
  static/scss/detail/header.scss
Labels: Waiting on Author

#351 fix error in console when no notification available
  static/js/notifications.js
Labels: Needs Review

#350 allow marketing user to add/edit slug for resource pages
  cms/models.py
  cms/models_test.py
Labels: Waiting on Author

#323 #324 Home Page: Base
  cms/factories.py
  cms/migrations/0019_home_page.py
  cms/migrations/0020_section_fixes.py
  cms/models.py
  cms/models_test.py
  cms/templates/cms/home_page.html
  courses/templates/partials/course-carousel.html
  ecommerce/views.py
  mitxpro/urls.py
  mitxpro/views_test.py
  static/js/home_page.js
Labels: Needs Review

#317 Trigger hubspot celery tasks where appropriate
  app.json
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/models_test.py
  ecommerce/signals.py
  ecommerce/task_helpers.py
  ecommerce/views.py
  ecommerce/views_test.py
  fixtures/autouse.py
  mitxpro/settings.py
  users/factories.py
  users/serializers.py
  users/serializers_test.py
Labels: Needs Review

#348 #258 Home Page: Inquire Now
  cms/migrations/0021_text_image_dark_theme.py
  cms/models.py
  cms/models_test.py
  courses/models_test.py
  courses/templates/partials/for-teams.html
  static/images/transparent-pixels-bg.png
  static/scss/detail/for-teams.scss
  static/scss/detail/who-should-enroll.scss
  static/scss/variables.scss
Labels: Needs Review

#305 asadiqbal08/mitxpro 274 - Link to Hubspot Form
  app.json
  courses/templates/catalog.html
  courses/templates/contact_us.html
  courses/templates/subscription.html
  courses/views.py
  mitxpro/settings.py
  mitxpro/templates/base.html
  static/scss/catalog/keep-me-posted.scss
Labels: Needs Review

#370 Added workers to pgbouncer
  Procfile
Labels: Needs Review

#352 #252 Home Page: Upcoming Courses
  cms/factories.py
  cms/migrations/0024_courseware_carousel_manual_contents.py
  cms/models.py
  cms/models_test.py
  cms/templates/cms/home_page.html
  courses/templates/course_detail.html
  courses/templates/partials/course-carousel.html
  courses/templates/partials/courseware-carousel-base.html
  static/scss/detail/courses-in-program.scss
Labels: Waiting on Author

#373 #372 Fix: Set HomePage as Parent of ResourcePage
  cms/models.py
Labels: Waiting on Author

#347 Additional serializers for hubspot
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/conftest.py
  ecommerce/signals.py
  ecommerce/views.py
  hubspot/__init__.py
  hubspot/api.py
  hubspot/api_test.py
  hubspot/management/commands/configure_hubspot_bridge.py
  hubspot/serializers.py
  hubspot/serializers_test.py
  hubspot/task_helpers.py
  hubspot/tasks.py
  hubspot/tasks_test.py
  mitxpro/settings.py
  users/serializers.py
  users/serializers_test.py
Labels: Waiting on Author

#334 SEO metadata for product pages
  cms/migrations/0025_add_wagtailmetadata.py
  cms/models.py
  cms/templates/cms/home_page.html
  courses/templates/course_detail.html
  courses/views_test.py
  mitxpro/settings.py
  mitxpro/templates/base.html
  requirements.in
  requirements.txt
Labels: Needs Review

#382 fix if only one date available
  courses/templates/partials/metadata-tiles.html
Labels: Needs Review

#377 #257 Homepage: About MIT xPRO
  cms/factories.py
  cms/migrations/0026_text_video_section.py
  cms/models.py
  cms/models_test.py
  cms/templates/cms/home_page.html
  cms/templates/partials/text-video-section.html
  static/js/text_video_section.js
  static/scss/detail/courses-in-program.scss
  static/scss/detail/testimonial-carousel.scss
  static/scss/detail/text-video-section.scss
  static/scss/layout.scss
  static/scss/slick.scss
Labels: Needs Review

#355 Added sanctionsLists to the exports request if it is set
  app.json
  compliance/api.py
  compliance/api_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#389 asadiqbal08/mitxpro-255 Companies slider
  cms/factories.py
  cms/migrations/0027_imagecarouselpage.py
  cms/models.py
  cms/models_test.py
  cms/templates/cms/home_page.html
  courses/templates/partials/companies-trust.html
  static/images/countries-trust-bg.png
  static/js/home_page.js
  static/scss/detail/companies-trust.scss
  static/scss/layout.scss
Labels: Needs Review

#400 asadiqbal08/mitxpro-374 Fix footer placement
  static/scss/layout.scss
Labels: Waiting on Author

#399 asadiqbal08/mitxpro-386 fix TOS link in footer
  mitxpro/templates/footer.html
Labels: Waiting on Author

#388 #383 Add Home Page Instructions to Readme
  README.md
Labels: Waiting on Author

#405 Added support for redirect on register existing email
  static/js/components/forms/RegisterEmailForm.js
  static/js/containers/pages/register/RegisterConfirmPage.js
  static/js/containers/pages/register/RegisterDetailsPage.js
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/containers/pages/register/RegisterEmailPage_test.js
Labels: Waiting on Author

#365 Enroll user in edX course runs on order success
  courses/migrations/0009_enrollment_statuses.py
  courses/models.py
  courseware/api.py
  courseware/api_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/management/commands/retry_edx_enrollment.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#395 #155 Integrate Wagtail Routing
  cms/management/commands/setup_index_pages.py
  cms/migrations/0028_course_program_index_pages.py
  cms/migrations/0029_setup_course_program_index_pages.py
  cms/models.py
  cms/models_test.py
  cms/templates/cms/product_page.html
  cms/templates/home_page.html
  cms/templates/partials/course-carousel.html
  cms/templates/partials/courseware-carousel-base.html
  cms/templates/partials/faculty-carousel.html
  cms/templates/partials/faqs.html
  cms/templates/partials/for-teams.html
  cms/templates/partials/hero.html
  cms/templates/partials/learning-outcomes.html
  cms/templates/partials/learning-techniques.html
  cms/templates/partials/metadata-tiles.html
  cms/templates/partials/subnav.html
  cms/templates/partials/target-audience.html
  cms/templates/partials/testimonial-carousel.html
  cms/templates/product_page.html
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  courses/templates/catalog.html
  courses/templates/catalog_card.html
  courses/templates/course_detail.html
  courses/templates/partials/subnav.html
  courses/urls.py
  courses/views.py
  courses/views_test.py
Labels: Needs Review

#401 add seed resource pages in CMS
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/management/commands/seed_data.py
  localdev/seed/resources/seed_data.json
Labels: Needs Review

#402 asadiqbal08/ mitxpro-272 Add hubspot form in footer
  app.json
  courses/views.py
  mitxpro/context_processors.py
  mitxpro/settings.py
  mitxpro/templates/footer.html
  static/images/arrow-circle-right.svg
  static/scss/footer.scss
Labels: Needs Review

#398 asadiqbal08/mitxpro-381 Integrate HubSpot in HomePage
  cms/templates/home_page.html
Labels: Waiting on Author

#412 Bumped drf version
  requirements.in
  requirements.txt
Labels: Waiting on Author

#390 Added template for config change request and PR checkbox
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/config_change_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: DevOps, Needs Review
