Repository mitodl/mitxpro, pull requests merged in 2019-03, with the labels that each got.

#23 Added RFC for storing course data
  docs/rfcs/0002-storing-course-data.md
Labels: Needs Review

#25 RFC for ecommerce infrastructure
  docs/rfcs/0001-ecommerce.md
Labels: Needs Review

#27 Added initial course models
  courses/migrations/0001_create_course_models.py
  courses/migrations/__init__.py
  courses/models.py
  mitxpro/models.py
  mitxpro/settings.py
  mitxpro/utils.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#22 Updated readme, un-required mailgun vars, added notebook container
  Dockerfile-nb
  README.md
  docker-compose-notebook.yml
  localdev/__init__.py
  localdev/app.ipynb.example
Labels: Waiting on Author

#39 Fixed courses django app
  courses/__init__.py
  courses/apps.py
Labels: Waiting on Author

#43 Adding github templates
  .github/pull_request_template.md
Labels: Waiting on Author

#20 Added RFC for Open edX auth integration
  docs/rfcs/0003-openedx-auth-integration.md
Labels: RFC

#50 Add rule to serve static files on dev environments
  config/nginx.conf
Labels: Needs Review

#44 Remove tox, move python test and linting to ./travis/python_tests.sh
  .travis.yml
  README.md
  conftest.py
  docker-compose.travis.yml
  mitxpro/templatetags/render_bundle_test.py
  mitxpro/views_test.py
  requirements.txt
  scripts/test/check_pip.sh
  scripts/test/detect_missing_migrations.sh
  scripts/test/no_auto_migrations.sh
  scripts/test/test_suite.sh
  test_requirements.txt
  tox.ini
  travis/python_tests.sh
Labels: Needs Review

#46 Added user/profile models, serializers, and read-only api
  README.md
  conftest.py
  docker-compose.yml
  docs/configure_open_edx.md
  fixtures/__init__.py
  fixtures/user.py
  mitxpro/permissions.py
  mitxpro/permissions_test.py
  mitxpro/settings.py
  mitxpro/test_utils.py
  mitxpro/test_utils_test.py
  mitxpro/urls.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  requirements.in
  requirements.txt
  test_requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/factories.py
  users/migrations/0001_add_user.py
  users/migrations/__init__.py
  users/models.py
  users/models_test.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Waiting on Author

#53 Added course model admin classes
  courses/admin.py
  courses/migrations/0002_course_run_date_blanks.py
  courses/models.py
Labels: Waiting on Author

#49 Added simple REST API for interacting with course data
  conftest.py
  courses/factories.py
  courses/migrations/0001_create_course_models.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  courses/urls.py
  courses/views.py
  courses/views_test.py
  fixtures/common.py
  fixtures/user.py
  mitxpro/settings.py
  mitxpro/urls.py
  requirements.txt
  test_requirements.txt
Labels: Waiting on Author

#56 Added mail app
  .travis.yml
  app.json
  conftest.py
  docker-compose.yml
  mail/__init__.py
  mail/api.py
  mail/api_test.py
  mail/apps.py
  mail/forms.py
  mail/migrations/__init__.py
  mail/templates/email_base.html
  mail/templates/email_debugger.html
  mail/templates/password_reset/body.html
  mail/templates/password_reset/subject.txt
  mail/templates/sample/body.html
  mail/templates/sample/subject.txt
  mail/templates/verification/body.html
  mail/templates/verification/subject.txt
  mail/templatetags/__init__.py
  mail/templatetags/timeago.py
  mail/urls.py
  mail/verification_api.py
  mail/verification_api_test.py
  mail/views.py
  mitxpro/settings.py
  mitxpro/settings_test.py
  pytest.ini
  requirements.in
  requirements.txt
  static/images/mit-logo.jpg
  test_requirements.txt
Labels: Waiting on Author

#54 Port authentication app from discussions
  authentication/__init__.py
  authentication/api.py
  authentication/api_test.py
  authentication/apps.py
  authentication/exceptions.py
  authentication/middleware.py
  authentication/middleware_test.py
  authentication/migrations/__init__.py
  authentication/pipeline/__init__.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/serializers_test.py
  authentication/strategy.py
  authentication/strategy_test.py
  authentication/templates/confirmation_sent.html
  authentication/templates/login.html
  authentication/templates/profile.html
  authentication/templates/register.html
  authentication/urls.py
  authentication/utils.py
  authentication/utils_test.py
  authentication/views.py
  authentication/views_test.py
  mitxpro/settings.py
  mitxpro/templates/base.html
  mitxpro/urls.py
  requirements.in
  requirements.txt
  test_requirements.txt
  users/admin.py
  users/factories.py
  users/models.py
  users/models_test.py
Labels: Waiting on Author

#36 Add RFC for ecommerce models
  docs/rfcs/0004-ecommerce-models.md
Labels: Needs Review, RFC

#57 Added redux-query
  .travis.yml
  Dockerfile-node
  mitxpro/templates/index.html
  mitxpro/views_test.py
  package.json
  static/js/actions/index.js
  static/js/containers/App.js
  static/js/containers/CheckboxPage.js
  static/js/containers/CheckboxPage_test.js
  static/js/reducers/index.js
  static/js/store/configureStore.js
  yarn.lock
Labels: Waiting on Author

#58 Added seed data command
  courses/migrations/0003_course_program_defaults.py
  courses/models.py
  localdev/seed/__init__.py
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/management/__init__.py
  localdev/seed/management/commands/__init__.py
  localdev/seed/management/commands/seed_data.py
  localdev/seed/resources/course_seed_data.json
  mitxpro/settings.py
  mitxpro/utils.py
  mitxpro/utils_test.py
Labels: Needs Review

#51 Adding wagtail
  cms/__init__.py
  cms/migrations/0001_initial.py
  cms/migrations/__init__.py
  cms/models.py
  cms/templates/cms/product_page.html
  mitxpro/settings.py
  mitxpro/settings_test.py
  mitxpro/urls.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#55 RFC: Bot-friendly front-end
  docs/rfcs/0004-bot-friendly-front-end.md
Labels: Needs Review

#41 Add models for ecommerce
  ecommerce/__init__.py
  ecommerce/apps.py
  ecommerce/migrations/0001_initial.py
  ecommerce/migrations/__init__.py
  ecommerce/models.py
  mitxpro/models.py
  mitxpro/settings.py
Labels: Waiting on Author

#59 Added basic course catalog
  Dockerfile-nb
  courses/templates/catalog.html
  courses/views.py
  courses/views_test.py
  localdev/seed/api.py
  localdev/seed/resources/course_seed_data.json
  mitxpro/templates/base.html
  mitxpro/templates/index.html
  mitxpro/urls.py
  mitxpro/views.py
  mitxpro/views_test.py
  package.json
  static/images/mit-dome.png
  static/scss/catalog.scss
  static/scss/layout.scss
  yarn.lock
Labels: Waiting on Author

#60 Add login UI
  .flowconfig
  flow-typed/npm/lodash_v4.x.x.js
  hot-reload-dev-server.js
  mitxpro/templates/base.html
  mitxpro/urls.py
  mitxpro/views_test.py
  package.json
  scripts/repl.js
  static/js/babelhook.js
  static/js/components/Header.js
  static/js/components/Header_test.js
  static/js/components/forms/login.js
  static/js/components/forms/login_test.js
  static/js/containers/App.js
  static/js/containers/pages/HomePage.js
  static/js/containers/pages/HomePage_test.js
  static/js/containers/pages/LoginPage.js
  static/js/flow/authTypes.js
  static/js/flow/declarations.js
  static/js/global_init.js
  static/js/lib/auth.js
  static/js/lib/queries/auth.js
  static/js/lib/queries/index.js
  static/js/lib/urls.js
  static/js/lib/urls_test.js
  static/js/reducers/index.js
  webpack.config.dev.js
  webpack.config.prod.js
  webpack.config.shared.js
  yarn.lock
Labels: Waiting on Author

#79 Added courseware Django app
  courseware/__init__.py
  courseware/apps.py
  courseware/migrations/__init__.py
  mitxpro/settings.py
Labels: Waiting on Author

#80 Fixed settings tests locally
  pytest.ini
Labels: Waiting on Author

#69 Ecommerce factories and utility functions
  ecommerce/admin.py
  ecommerce/admin_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/apps.py
  ecommerce/factories.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/test_utils.py
  mitxpro/utils.py
  mitxpro/utils_test.py
Labels: Waiting on Author

#84 Fixed hijack release redirect url
  mitxpro/settings.py
Labels: Waiting on Author

#81 Added API call to create edX user when xpro user is created
  README.md
  app.json
  conftest.py
  courseware/api.py
  courseware/api_test.py
  courseware/constants.py
  courseware/migrations/0001_add_oauth_application.py
  courseware/migrations/0002_add_courseware_user.py
  courseware/models.py
  courseware/tasks.py
  courseware/tasks_test.py
  docs/configure_open_edx.md
  fixtures/autouse.py
  mitxpro/settings.py
  pytest.ini
  users/models.py
  users/models_test.py
Labels: Waiting on Author

#86 RFC for ecommerce REST APIs
  docs/rfcs/0005-ecommerce-rest-api.md
Labels: Needs Review, RFC

#52 Add RFC for coupons
  docs/rfcs/0005-coupons.md
Labels: Needs Review, RFC

#90 Added MAILGUN_SENDER_DOMAIN and removed MAILGUN_URL from required set…
  .env.example
  README.md
  app.json
  docker-compose.travis.yml
Labels: Waiting on Author

#92 Bump docker to stretch debian
  Dockerfile
Labels: Waiting on Author

#88 Combined auth steps for creating user and setting pw, name
  authentication/exceptions.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#93 Fix app.json validity
  app.json
Labels: Needs Review

#87 Models for edX auth tokens
  courseware/migrations/0003_add_edx_auth.py
  courseware/models.py
Labels: Waiting on Author

#96 Move template tag tests out of templatetags module
  mitxpro/tests/__init__.py
  mitxpro/tests/render_bundle_test.py
Labels: Waiting on Author

#77 Coupon functions and model changes
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/migrations/0002_coupon_additional_fields.py
  ecommerce/models.py
Labels: Needs Review

#98 Fixed binding error
  static/js/containers/pages/LoginPage.js
Labels: Waiting on Author

#94 Create OpenEdxApiAuth when the user is created
  .env.example
  .travis.yml
  app.json
  authentication/api.py
  authentication/api_test.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/strategy.py
  courses/admin.py
  courseware/admin.py
  courseware/api.py
  courseware/api_test.py
  courseware/exceptions.py
  courseware/factories.py
  courseware/models.py
  courseware/tasks.py
  courseware/tasks_test.py
  courseware/urls.py
  courseware/views.py
  courseware/views_test.py
  docker-compose-notebook.yml
  docker-compose.override.yml
  docker-compose.travis.yml
  docker-compose.yml
  docs/configure_open_edx.md
  mail/verification_api_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  pytest.ini
  test_requirements.txt
  users/api.py
  users/api_test.py
Labels: Needs Review

#100 Added course enrollment button to course detail page
  courses/factories.py
  courses/migrations/0004_change_courseware_url_field.py
  courses/models.py
  courses/models_test.py
  courses/serializers_test.py
  courses/templates/catalog.html
  courses/templates/catalog_card.html
  courses/templates/course_detail.html
  courses/urls.py
  courses/views.py
  courses/views_test.py
  courseware/api.py
  courseware/api_test.py
  courseware/exceptions.py
  courseware/utils.py
  localdev/seed/resources/course_seed_data.json
  mitxpro/urls.py
  requirements.in
  requirements.txt
Labels: Needs Review

#95 Checkout and order fulfillment ecommerce REST APIs
  app.json
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/constants.py
  ecommerce/exceptions.py
  ecommerce/permissions.py
  ecommerce/permissions_test.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/models.py
  mitxpro/settings.py
  mitxpro/urls.py
Labels: Waiting on Author

#97 Basket REST API
  courses/models.py
  courses/models_test.py
  ecommerce/admin.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/urls.py
  mitxpro/utils.py
Labels: Waiting on Author
