Repository mitodl/mitxpro, pull requests merged in 2019-09, with the labels that each got.

#1010 #595 Sort dashboard courses
  courses/api.py
  courses/api_test.py
Labels: Waiting on Author

#1086 styling of file name
  static/scss/voucher.scss
Labels: Waiting on Author

#1058 Added cron job to retry edx enrollments
  app.json
  courses/management/utils.py
  courseware/api.py
  courseware/api_test.py
  courseware/constants.py
  courseware/exceptions.py
  courseware/management/commands/retry_edx_enrollment.py
  courseware/tasks.py
  courseware/tasks_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#1069 asadiqbal08/mitxpro 877 - Certificates: automate course certificate creation
  app.json
  courses/management/commands/sync_grades_and_certificates.py
  courses/migrations/0021_courserungrade_set_by_admin.py
  courses/models.py
  courses/tasks.py
  courses/utils.py
  mitxpro/settings.py
Labels: Needs Review

#1064 Added cron job to repair courseware users
  app.json
  courseware/api.py
  courseware/api_test.py
  courseware/factories.py
  courseware/management/commands/repair_missing_courseware_records.py
  courseware/tasks.py
  mitxpro/envs.py
  mitxpro/settings.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  users/models.py
  users/models_test.py
Labels: Waiting on Author

#1075 Added edX unenrollment capability
  courses/management/utils.py
  courses/models.py
  courseware/api.py
  courseware/api_test.py
  mitxpro/models.py
  requirements.in
  requirements.txt
Labels: Needs Review

#1061 View Certificate button and Wagtail handling
  cms/models.py
  cms/templates/certificate_page.html
  cms/views_test.py
  courses/factories.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  mitxpro/settings.py
  static/images/certificates/certificate.png
  static/images/certificates/icon-facebook.svg
  static/images/certificates/icon-linkedin.svg
  static/images/certificates/icon-print.svg
  static/images/certificates/icon-twitter.svg
  static/images/certificates/mitx-pro-logo-cer.png
  static/images/certificates/share-image.png
  static/images/certificates/transparent-mit-xpro-logo.png
  static/js/containers/pages/DashboardPage.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
  static/scss/certificates/certificate.scss
  static/scss/dashboard.scss
Labels: Waiting on Author

#1090 Add explanation text to B2B purchase and receipt pages
  static/js/components/B2BExplanation.js
  static/js/components/Expandable.js
  static/js/components/Expandable_test.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/scss/checkout.scss
  static/scss/expandable.scss
  static/scss/layout.scss
Labels: Needs Review

#1094 Changed username generation to be based on users' full names
  authentication/api.py
  authentication/api_test.py
  authentication/exceptions.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  users/api.py
  users/api_test.py
  users/constants.py
  users/factories.py
  users/migrations/0001_add_user.py
  users/migrations/0010_remove_username_ulid_default.py
  users/migrations/0011_change_username_max_len_50.py
  users/models.py
  users/models_test.py
  users/utils.py
  users/utils_test.py
Labels: Waiting on Author

#1109 Remove reference prefix environment variable, use environment instead
  app.json
  b2b_ecommerce/api_test.py
  b2b_ecommerce/constants.py
  b2b_ecommerce/models.py
  b2b_ecommerce/models_test.py
  b2b_ecommerce/views_test.py
  ecommerce/api_test.py
  ecommerce/constants.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/views_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#1102 Coupons for refunded orders should not be valid
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#1111 Add Order.total_price_paid and populate from coupon discount and product prices
  ecommerce/api.py
  ecommerce/factories.py
  ecommerce/migrations/0017_order_total_price_paid.py
  ecommerce/models.py
  mitxpro/utils_test.py
Labels: Waiting on Author

#1115 Add payment_type and payment_transaction for coupons created by B2B purchases
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
Labels: Waiting on Author

#1055 Implement discount codes for B2B purchases
  b2b_ecommerce/admin.py
  b2b_ecommerce/admin_test.py
  b2b_ecommerce/api.py
  b2b_ecommerce/conftest.py
  b2b_ecommerce/factories.py
  b2b_ecommerce/migrations/0003_coupons.py
  b2b_ecommerce/migrations/0004_coupon_company_blank.py
  b2b_ecommerce/models.py
  b2b_ecommerce/models_test.py
  b2b_ecommerce/urls.py
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/admin.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/templates/b2b_receipt/body.html
  mail/views.py
  static/js/components/B2BPurchaseSummary.js
  static/js/components/B2BPurchaseSummary_test.js
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/forms/B2BPurchaseForm_test.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/queries/ecommerceAdmin.js
  static/scss/checkout.scss
Labels: Waiting on Author

#1112 #1099 Program certificate links and view
  cms/constants.py
  cms/migrations/0042_certificate_index_page.py
  cms/migrations/0043_setup_certificate_index_page.py
  cms/models.py
  cms/templates/certificate_page.html
  cms/views_test.py
  courses/factories.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  static/js/containers/pages/DashboardPage.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
  static/scss/dashboard.scss
Labels: Needs Review

#1120 #980 Coupons: product selection improvement
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  static/js/components/forms/CouponForm.js
  static/js/components/forms/CouponForm_test.js
  static/js/containers/pages/admin/CreateCouponPage.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/ecommerce-admin.scss
Labels: Needs Review

#1131 Lowered max username length to 30 (in code, not in db)
  users/api_test.py
  users/constants.py
  users/models.py
Labels: Waiting on Author

#1076 asadiqbal08/Mitxpro-1036 Open a FancyBox over clicking Watch Now button.
  cms/templates/home_page.html
  cms/templates/partials/text-video-section.html
  static/css/vendor/jquery.fancybox.min.css
  static/js/hero.js
  static/js/vendor/jquery.fancybox.min.js
  static/scss/detail/text-video-section.scss
Labels: Waiting on Author

#1116 asadiqbal08/mitxpro-1059 Add a "is_active" field to the product model
  ecommerce/admin.py
  ecommerce/migrations/0018_product_is_active.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1125 Adding validation to proper Nginx config and full HTML response
  config/nginx.conf
  config/nginx.conf.erb
Labels: DevOps, Needs Review

#1124 Change decimal places for amount from 2 to 5 and add validation
  ecommerce/conftest.py
  ecommerce/factories.py
  ecommerce/migrations/0018_amount_more_decimal_places.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  hubspot/serializers.py
  hubspot/serializers_test.py
Labels: Waiting on Author

#1126 Updated sync_grades_and_certificates params
  courses/management/commands/sync_grades_and_certificates.py
Labels: Waiting on Author

#1139 Fix migrations by renaming one conflicting migration to happen later
  ecommerce/migrations/0019_amount_more_decimal_places.py
Labels: Waiting on Author

#1127 asadiqbal08/mitxpro-1122 - Add validation over name field
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  static/js/components/forms/ProfileFormFields.js
  static/js/components/forms/RegisterDetailsForm_test.js
Labels: Waiting on Author

#1140 #1123 certificate validation link
  cms/models.py
  cms/templates/certificate_page.html
  static/scss/certificates/certificate.scss
Labels: Waiting on Author

#1095 Update UI for selecting products in B2B purchase form
  .flowconfig
  package.json
  static/js/components/B2BPurchaseSummary.js
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/input/ProductSelector.js
  static/js/components/input/ProductSelectorMenu.js
  static/js/components/input/ProductSelectorMenu_test.js
  static/js/components/input/ProductSelector_test.js
  static/js/lib/ecommerce.js
  static/scss/checkout.scss
  yarn.lock
Labels: Waiting on Author

#1143 asadiqbal08/mitxpro-953 Introduce FormErrors for ecommerce coupons
  static/js/components/forms/CouponForm.js
Labels: Waiting on Author

#1117 change from email for admin notifications
  authentication/pipeline/compliance.py
  ecommerce/utils.py
Labels: Needs Review

#1146 asadiqbal08/mitxpro-1148 ProgramCertificate will not create for standalone course
  courses/__init__.py
  courses/signals.py
  courses/signals_test.py
  courses/utils.py
Labels: Needs Review

#1134 email verification message updated
  static/js/containers/pages/register/RegisterConfirmSentPage.js
  static/js/containers/pages/register/RegisterConfirmSentPage_test.js
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/containers/pages/register/RegisterEmailPage_test.js
  static/js/containers/pages/register/RegisterPages.js
  static/js/lib/auth.js
  static/js/lib/selectors.js
  static/js/lib/selectors_test.js
  static/js/lib/urls.js
  static/scss/auth.scss
Labels: Needs Review

#1155 Update program serializer
  courses/factories.py
  courses/serializers.py
  courses/serializers_test.py
Labels: Needs Review

#1157 Added bulk assignment CSV download to bulk coupon form
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0020_add_bulk_coupon_assignment.py
  ecommerce/models.py
  ecommerce/urls.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  static/js/components/forms/BulkEnrollmentForm.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/urls.js
Labels: Waiting on Author

#1166 Updated several admin classes (course run enrollment, etc)
  b2b_ecommerce/admin.py
  courses/admin.py
  courseware/admin.py
  ecommerce/admin.py
  mitxpro/admin.py
Labels: Waiting on Author

#1161 Allow anonymous access to course list and detail API
  courses/views.py
  courses/views_test.py
Labels: Waiting on Author
