Repository mitodl/mitxpro, pull requests merged in 2019-08, with the labels that each got.

#930 #929 Test fixes for program more dates
  courses/models_test.py
Labels: Waiting on Author

#851 #679 Set an HTML title on React pages
  package.json
  static/js/constants.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/admin/BulkEnrollmentPage.js
  static/js/containers/pages/admin/CreateCouponPage.js
  static/js/containers/pages/login/LoginEmailPage.js
  static/js/containers/pages/login/LoginForgotPasswordConfirmPage.js
  static/js/containers/pages/login/LoginForgotPasswordPage.js
  static/js/containers/pages/login/LoginPasswordPage.js
  static/js/containers/pages/profile/EditProfilePage.js
  static/js/containers/pages/profile/EditProfilePage_test.js
  static/js/containers/pages/profile/ViewProfilePage.js
  static/js/containers/pages/profile/ViewProfilePage_test.js
  static/js/containers/pages/register/RegisterConfirmPage.js
  static/js/containers/pages/register/RegisterDeniedPage.js
  static/js/containers/pages/register/RegisterDetailsPage.js
  static/js/containers/pages/register/RegisterEmailPage.js
  static/js/containers/pages/register/RegisterErrorPage.js
  static/js/containers/pages/register/RegisterExtraDetailsPage.js
  yarn.lock
Labels: Waiting on Author

#931 JS dependencies updated
  package.json
  yarn.lock
Labels: Needs Review

#928 remove redundant code
  cms/templates/catalog_page.html
  cms/templates/partials/card_details_bottom.html
  cms/templates/partials/card_details_top.html
  cms/templates/partials/catalog-card.html
  cms/templates/partials/catalog_card.html
  cms/templates/partials/featured_card.html
Labels: Waiting on Author

#934 Added explicit buffer size to uWSGI for cookie size issues
  uwsgi.ini
Labels: Waiting on Author

#933 Change exact search to contains search
  voucher/conftest.py
  voucher/utils.py
  voucher/utils_test.py
Labels: Waiting on Author

#916 show past enrollments on dashboard
  courses/api.py
  courses/api_test.py
  courses/models.py
  courses/models_test.py
  courses/views.py
  courses/views_test.py
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/factories/course.js
  static/js/flow/courseTypes.js
  static/js/lib/courses.js
  static/scss/dashboard.scss
Labels: Waiting on Author

#944 asadiqbal08/mitxpro-903 Removed un existent field 'description'
  courses/admin.py
Labels: Waiting on Author

#943 fix spaces around coupon code
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/CheckoutPage.js
Labels: Waiting on Author

#937 Fix incorrect password redirecting a user to the create account error page
  authentication/serializers.py
  authentication/views_test.py
Labels: Needs Review

#956 Add support for IE11
  static/js/hero.js
  webpack.config.shared.js
Labels: Needs Review

#959 Include specific libraries which need transpiling
  webpack.config.shared.js
Labels: Needs Review

#911 asadiqbal08/mitxpro - CMS: customize certificates
  cms/constants.py
  cms/factories.py
  cms/management/commands/setup_index_pages.py
  cms/migrations/0041_certificatepage_signatoryindexpage_signatorypage.py
  cms/models.py
  cms/models_test.py
  cms/templates/certificate_page.html
  static/images/certificates/certificate-logo.png
  static/images/certificates/certificate-mit-logo.png
  static/images/certificates/sign.png
  static/scss/certificates/certificate.scss
  static/scss/layout.scss
Labels: Waiting on Author

#917 Add b2b_ecommerce app to handle bulk enrollment code purchases
  b2b_ecommerce/__init__.py
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
  b2b_ecommerce/constants.py
  b2b_ecommerce/factories.py
  b2b_ecommerce/migrations/0001_initial.py
  b2b_ecommerce/migrations/0002_order_coupon_payment.py
  b2b_ecommerce/migrations/__init__.py
  b2b_ecommerce/models.py
  b2b_ecommerce/models_test.py
  b2b_ecommerce/serializers.py
  b2b_ecommerce/urls.py
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/constants.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/test_utils.py
  ecommerce/utils.py
  ecommerce/utils_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/settings.py
  mitxpro/urls.py
Labels: Waiting on Author

#945 asadiqbal08/mitxpro-925 "More Dates" on Course Product page doesn't work in Safari
  cms/templates/partials/metadata-tiles.html
Labels: Waiting on Author

#946 profile add highest level of education
  authentication/serializers.py
  hubspot/management/commands/configure_hubspot_bridge.py
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EditProfileForm_test.js
  static/js/components/forms/ProfileFormFields.js
  static/js/constants.js
  static/js/containers/pages/profile/EditProfilePage.js
  static/js/containers/pages/profile/EditProfilePage_test.js
  static/js/containers/pages/profile/ViewProfilePage.js
  static/js/factories/user.js
  static/js/flow/authTypes.js
  static/scss/common.scss
  users/migrations/0009_profile_highest_education.py
  users/models.py
  users/serializers.py
  users/views_test.py
Labels: Waiting on Author

#969 Make checkbox CSS rule more specific to catalog page
  static/scss/collapsible.scss
Labels: Needs Review

#970 Changed edX enrollment mode from audit to professional
  app.json
  courseware/api.py
  courseware/api_test.py
  courseware/constants.py
  docker-compose.yml
  mitxpro/settings.py
  mitxpro/test_utils.py
  mitxpro/test_utils_test.py
Labels: Waiting on Author

#989 Fix profile edit form
  static/js/containers/pages/profile/EditProfilePage.js
  static/js/containers/pages/profile/EditProfilePage_test.js
Labels: Waiting on Author

#977 Backend work for b2b enrollment code purchases
  b2b_ecommerce/factories.py
  b2b_ecommerce/urls.py
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  courses/serializers.py
  courses/serializers_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
Labels: Needs Review

#998 Bumped django
  requirements.in
  requirements.txt
Labels: Waiting on Author

#963 Improved Django admin UI for several coupon-related ecommerce models
  ecommerce/admin.py
Labels: Waiting on Author

#996 Fixed bug where 'edx_enrolled' flag was not being updated by commands
  courses/management/utils.py
Labels: Waiting on Author

#990 Added new edX enrollment command options and refactored command helpers
  courses/management/commands/defer_enrollment.py
  courses/management/commands/refund_enrollment.py
  courses/management/commands/transfer_enrollment.py
  courses/management/utils.py
  ecommerce/api.py
  ecommerce/management/commands/retry_edx_enrollment.py
  ecommerce/utils.py
  mitxpro/utils.py
  users/api.py
  users/api_test.py
Labels: Waiting on Author

#999 Bump js dependencies
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/containers/pages/admin/CreateCouponPage.js
  yarn.lock
Labels: Waiting on Author

#997 Enabled case-insensitive email search in management commands
  mitxpro/utils.py
  mitxpro/utils_test.py
  users/api.py
  users/api_test.py
Labels: Waiting on Author

#954 #918 CourseRun Expiration Date
  courses/factories.py
  courses/migrations/0017_courserun_expiration_date.py
  courses/migrations/0018_backpopulate_courserun_expiration_date.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/lib/courses.js
  static/scss/dashboard.scss
  static/scss/variables.scss
Labels: Waiting on Author

#958 Add pages for bulk enrollment code purchase and a receipt page to download codes
  b2b_ecommerce/urls.py
  static/js/components/B2BPurchaseSummary.js
  static/js/components/B2BPurchaseSummary_test.js
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/forms/B2BPurchaseForm_test.js
  static/js/components/input/ProductSelector.js
  static/js/components/input/ProductSelector_test.js
  static/js/containers/App.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/js/containers/pages/b2b/B2BReceiptPage_test.js
  static/js/containers/pages/b2b/EcommerceBulkPages.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/ecommerce.js
  static/js/lib/urls.js
  static/scss/checkout.scss
Labels: Waiting on Author

#974 asadiqbal08/mitxpro-873 Coure/Program Certificate models
  courses/admin.py
  courses/migrations/0019_courseruncertificate_courserungrade_courserungradeaudit_programcertificate.py
  courses/models.py
Labels: Waiting on Author

#1004 Update program api
  cms/factories.py
  courses/serializers.py
  courses/serializers_test.py
Labels: Waiting on Author

#1042 voucher dropdown update
  courses/models.py
  voucher/conftest.py
  voucher/utils.py
  voucher/utils_test.py
  voucher/views_test.py
Labels: Needs Review, Waiting on Author

#1003 Send email after enrollment code order is fulfilled
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
  b2b_ecommerce/serializers.py
  b2b_ecommerce/views_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/constants.py
  mail/templates/b2b_receipt/body.html
  mail/templates/b2b_receipt/subject.txt
  mail/views.py
  mitxpro/utils.py
  mitxpro/utils_test.py
Labels: Waiting on Author

#1043 link to support center on voucher resubmit page
  static/scss/voucher.scss
  voucher/templates/resubmit.html
Labels: Needs Review

#1040 Add checkout URL to B2B enrollment code checkout CSV
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/api.py
  ecommerce/mail_api.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  voucher/views.py
  voucher/views_test.py
Labels: Waiting on Author

#1048 Do not check for hubspot errors without an api key
  hubspot/tasks.py
  hubspot/tasks_test.py
Labels: Waiting on Author

#1045 Remove B2B order fulfillment API, merge with ecommerce order fulfillment API
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
  b2b_ecommerce/models.py
  b2b_ecommerce/urls.py
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/api.py
  ecommerce/models.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1032 #1029 Course run certificate management command
  app.json
  courses/management/commands/sync_grades_and_certificates.py
  courses/migrations/0020_course_run_grade_optional_letter_grade.py
  courses/models.py
  courses/utils.py
  courseware/api.py
  mitxpro/settings.py
Labels: Waiting on Author

#1053 Add id to Hubspot product title
  ecommerce/__init__.py
  ecommerce/admin.py
  ecommerce/apps.py
  hubspot/serializers.py
  hubspot/serializers_test.py
Labels: Waiting on Author

#1070 Fixed bug in sync_grades_and_certificates command
  courses/utils.py
Labels: Waiting on Author

#1062 asadiqbal08/mitxpro-1036 Homepage: open "Watch Now" video in a lightbox
  cms/templates/partials/text-video-section.html
  static/js/hero.js
  static/js/text_video_section.js
  static/scss/detail/text-video-section.scss
Labels: Waiting on Author

#1024 Add modal selection widget for enrollment code purchase form
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/forms/B2BPurchaseForm_test.js
  static/js/components/input/ProductSelector.js
  static/js/components/input/ProductSelectorMenu.js
  static/js/components/input/ProductSelectorMenu_test.js
  static/js/components/input/ProductSelector_test.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/ecommerce.js
  static/scss/checkout.scss
Labels: Needs Review
