Repository mitodl/mitxpro, pull requests merged in 2019-10, with the labels that each got.

#1169 Changed catalog logic to show courses with past start dates but future enrollment end dates
  cms/models.py
  cms/utils.py
  cms/utils_test.py
  courses/factories.py
  courses/models.py
  courses/models_test.py
Labels: Waiting on Author

#1144 MIT xPRO - 1063 Fix redirect issue while creating account
  static/js/containers/pages/login/LoginEmailPage.js
  static/js/containers/pages/login/LoginEmailPage_test.js
Labels: Waiting on Author

#1150 performance optimization on catalog page
  cms/models.py
  courses/models.py
Labels: Needs Review

#1133 asadiqbal08/mitxpro-1104 - Update Forgot Password message
  static/js/containers/pages/login/LoginForgotPasswordPage.js
  static/js/containers/pages/login/LoginForgotPasswordPage_test.js
  static/js/containers/pages/register/RegisterConfirmSentPage.js
  static/js/containers/pages/register/RegisterConfirmSentPage_test.js
  static/scss/auth.scss
Labels: Needs Review

#1178 Fixed Product admin
  ecommerce/admin.py
Labels: Waiting on Author

#1160 Fixing verification rendering
  config/nginx.conf
  config/nginx.conf.erb
  fastly_verification.html
Labels: DevOps, Waiting on Author

#1149 #978 Admin interface for export compliance result
  compliance/admin.py
  users/utils.py
  users/utils_test.py
Labels: Waiting on Author

#1187 asadiqbal08/mitxpro-1162 Display account created date and last login date on user admin page
  users/admin.py
Labels: Waiting on Author

#1177 Add instructors to programs API
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
Labels: Waiting on Author

#1191 product as raw field in product version
  ecommerce/admin.py
Labels: Waiting on Author

#1201 #1200 Course certificate generation task fix
  courses/utils.py
Labels: Waiting on Author

#1194 fix catalog page for IE11
  static/scss/catalog/body.scss
Labels: Waiting on Author

#1158 retire user management command
  requirements.in
  requirements.txt
  users/management/commands/retire_users.py
  users/management/commands/retire_users_test.py
Labels: Waiting on Author

#1204 #1203 Exports inquiry admin action fix
  compliance/admin.py
Labels: Needs Review

#1206 #1205 certificate button 404 fix
  courses/api.py
  courses/serializers.py
Labels: Waiting on Author

#1196 Add course topics
  courses/admin.py
  courses/migrations/0022_topics.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/resources/seed_data.json
Labels: Waiting on Author

#1154 MIT xPRO - 1153 Fix broken commands in handbook and added in mitxpro
  README.md
  docs/configure_open_edx.md
Labels: Needs Review

#1197 Add topics to programs API
  courses/serializers.py
  courses/serializers_test.py
Labels: Waiting on Author

#1202 asadiqbal08/mitxpro-1195 Fix the layout issue for IE over dashboard
  static/scss/dashboard.scss
Labels: Waiting on Author

#1209 add order optional parameter in refund_enrollment command
  courses/management/commands/refund_enrollment.py
  courses/management/utils.py
  courses/management/utils_tests.py
Labels: Waiting on Author

#1218 Updated metadata for new attempt at TLS cert generation
  fastly_verification.html
Labels: DevOps, Needs Review

#1190 asadiqbal08/mitxpro-1174 Added the zendesk help widget to project
  app.json
  mitxpro/context_processors.py
  mitxpro/settings.py
  mitxpro/templates/base.html
Labels: Needs Review

#1210 asadiqbal08/mitxpro-1192 Show time along with date for upcoming courses.
  static/js/lib/courses.js
  static/js/lib/courses_test.js
  static/js/lib/util.js
Labels: Needs Review

#1230 Filter courses, runs, and programs based on product and live status
  courses/factories.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views.py
  courses/views_test.py
Labels: Waiting on Author

#1136 #843 Checkout: non-200 responses
  mitxpro/templates/base.html
  static/js/containers/pages/CheckoutPage.js
Labels: Needs Review

#1221 MIT xPRO - 1119 Watch Now button should come only in the presence of video
  cms/templates/partials/hero.html
  cms/views_test.py
Labels: Waiting on Author

#1228 Expand clickable area for user menu
  static/scss/user-menu.scss
Labels: Waiting on Author

#1193 add sorting for all ecommerce adming pages
  ecommerce/api_test.py
  ecommerce/models.py
  ecommerce/views.py
  static/js/components/forms/BulkEnrollmentForm.js
  static/js/components/forms/BulkEnrollmentForm_test.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Needs Review

#1241 Added custom metadata options in mail API, added metadata to bulk enrollment emails
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/api.py
  ecommerce/constants.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/utils.py
  ecommerce/views.py
  mail/api.py
  mail/api_test.py
  voucher/views.py
Labels: Waiting on Author

#1258 asadiqbal08/mitxpro-Fix the landscape mode issue while Printing
  cms/templates/certificate_page.html
  static/scss/certificates/certificate.scss
Labels: Needs Review

#1266 Changing default database addon to be standard-0 to allow for more co…
  app.base.json
  app.json
  mitxpro/settings_test.py
Labels: DevOps, Waiting on Author

#1249 #1232 External course CMS page
  cms/factories.py
  cms/migrations/0044_external_course_cms_page.py
  cms/models.py
  cms/models_test.py
  cms/templates/catalog_page.html
  cms/templates/partials/card_details_top.html
  cms/templates/partials/hero.html
  cms/templates/partials/metadata-tiles.html
  cms/utils.py
  cms/utils_test.py
Labels: Waiting on Author

#1264 #1250 Add SignatoryIndexPage from CMS
  cms/models.py
Labels: Waiting on Author

#1263 #1222 Program next run date comes from first course
  cms/models.py
  cms/templates/partials/hero.html
  cms/views_test.py
  courses/models.py
  courses/models_test.py
  courses/views_test.py
Labels: Waiting on Author

#1267 #1265 Certificate generation only on passed status
  courses/factories.py
  courses/utils.py
  courses/utils_test.py
Labels: Needs Review
