Repository mitodl/mitxpro, pull requests merged in 2019-11, with the labels that each got.

#1281 #1280 External course page apply now button fix
  cms/templates/partials/hero.html
Labels: Needs Review

#1270 Changed product coupon assignment match to be case-insensitive
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#1257 Vouchers: sort matching courseruns by similarity
  voucher/templates/enroll.html
  voucher/utils.py
  voucher/utils_test.py
  voucher/views.py
  voucher/views_test.py
Labels: Needs Review

#1285 #1245 Add search to product and version admin
  ecommerce/admin.py
Labels: Waiting on Author

#1286 asadiqbal08/mitxpro-1247- Display the text id and price in product list_display
  ecommerce/admin.py
Labels: Waiting on Author

#1262 Enabled coupon assignment and messaging from coupon assignment Sheets
  app.json
  docker-compose-notebook.yml
  docker-compose.yml
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0021_bulk_coupon_assignment_from_sheets.py
  ecommerce/migrations/0022_changed_bulk_assignment_flags.py
  ecommerce/models.py
  ecommerce/views.py
  ecommerce/views_test.py
  mail/api.py
  mail/api_test.py
  mitxpro/settings.py
  mitxpro/utils.py
  sheets/api.py
  sheets/api_test.py
  sheets/constants.py
  sheets/exceptions.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_request_row.py
  sheets/migrations/0002_nullable_google_api_auth_user.py
  sheets/models.py
  sheets/tasks.py
  sheets/tasks_test.py
  sheets/utils.py
  sheets/utils_test.py
  sheets/views.py
Labels: Waiting on Author

#1299 Added setting for controlling edx API client request timeout
  app.json
  courseware/api.py
  mitxpro/settings.py
Labels: Waiting on Author

#1304 #1301 Fix certificate view (4 signatures inline)
  cms/templates/certificate_page.html
  static/scss/certificates/certificate.scss
Labels: Needs Review

#1298 Add status to deal sync, add birth year to custom props
  hubspot/api.py
  hubspot/api_test.py
  hubspot/management/commands/configure_hubspot_bridge.py
  hubspot/serializers.py
  hubspot/serializers_test.py
Labels: Waiting on Author

#1303 #1276 Configurable CSRF_TRUSTED_ORIGINS env var
  app.json
  mitxpro/envs.py
  mitxpro/settings.py
  mitxpro/settings_test.py
Labels: Waiting on Author

#1242 MIT xPRO - 1226 Fix forgot password form while logged in
  static/js/containers/pages/login/LoginForgotPasswordConfirmPage_test.js
  static/js/containers/pages/login/LoginForgotPasswordPage_test.js
  static/js/lib/queries/auth.js
Labels: Needs Review

#1308 Filter invalid runs from selected runs list
  ecommerce/serializers.py
  ecommerce/serializers_test.py
Labels: Needs Review

#1287 #1259 Usernamify fix for Turkish characters
  users/utils.py
  users/utils_test.py
Labels: Waiting on Author

#1279 Update Pillow, Wagtail
  cms/migrations/0031_setup_catalog_page.py
  cms/migrations/0043_setup_certificate_index_page.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1311 Added logic to update Sheets with coupon assignment message delivery status
  app.json
  ecommerce/admin.py
  ecommerce/factories.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0021_bulk_coupon_assignment_from_sheets.py
  ecommerce/migrations/0021_coupon_assignment_statuses_and_flags.py
  ecommerce/migrations/0022_changed_bulk_assignment_flags.py
  ecommerce/models.py
  ecommerce/views.py
  ecommerce/views_test.py
  mail/constants.py
  mitxpro/envs.py
  mitxpro/settings.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  sheets/admin.py
  sheets/api.py
  sheets/api_test.py
  sheets/configure_sheets_client.md
  sheets/constants.py
  sheets/mail_api.py
  sheets/management/__init__.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/update_assignment_message_statuses.py
  sheets/management/utils.py
  sheets/migrations/0003_remove_coupongenerationrequest_spreadsheet_updated.py
  sheets/models.py
  sheets/tasks.py
  sheets/utils.py
Labels: Needs Review

#1292 #1243 Set user context for Sentry
  static/js/components/Header.js
Labels: Waiting on Author

#1252 asadiqbal08/mitxpro-1215 - Management Command to revoke Program/Run Certificates.
  cms/views_test.py
  courses/admin.py
  courses/management/commands/revoke_certificate.py
  courses/migrations/0023_revoke_certificate.py
  courses/models.py
  courses/utils.py
Labels: Waiting on Author

#1229 #1173 Purchase event tracking through GTM
  app.json
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/context_processors.py
  mitxpro/serializers.py
  mitxpro/settings.py
  mitxpro/templates/base.html
  mitxpro/templates/partials/gtm_body.html
  mitxpro/templates/partials/gtm_head.html
  mitxpro/views.py
  mitxpro/views_test.py
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/DashboardPage.js
  static/js/flow/declarations.js
  static/js/global_init.js
Labels: Waiting on Author

#1323 Configured coupon request sheet to be populated by form
  app.json
  mitxpro/settings.py
  mitxpro/settings_test.py
  sheets/admin.py
  sheets/api.py
  sheets/api_test.py
  sheets/conftest.py
  sheets/constants.py
  sheets/factories.py
  sheets/management/commands/create_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_request_row.py
  sheets/management/commands/setup_sheet_update_webhook.py
  sheets/management/utils.py
  sheets/migrations/0004_rename_transaction_id.py
  sheets/models.py
  sheets/tasks.py
  sheets/tasks_test.py
  sheets/utils.py
  sheets/utils_test.py
Labels: Waiting on Author

#1328 asadiqbal08/mitxpro-1327 TypeError '<' not supported
  courses/models.py
Labels: Waiting on Author

#1335 Add X-Forwarded-Host setting and make it configurable
  app.json
  mitxpro/settings.py
Labels: DevOps, Needs Review

#1310 Not check for expired run if there is --force flag
  courses/management/commands/defer_enrollment.py
  courses/management/commands/transfer_enrollment.py
Labels: Waiting on Author

#1347 Fixed Google Sheets file watch request
  sheets/api.py
Labels: Needs Review

#1354 Changed coupon assignment sheet handling to fetch one at a time
  sheets/api.py
  sheets/tasks.py
Labels: Waiting on Author

#1305 MIT xPRO - 1033 Vouchers: seed data for vouchers
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/resources/seed_data.json
  localdev/seed/serializers.py
  mitxpro/envs.py
  mitxpro/settings.py
Labels: Needs Review
