Repository mitodl/mitxpro, pull requests merged in 2020-09, with the labels that each got.

#1892 asadiqbal08/mitxpro Product page microdata
  cms/templates/product_page.html
  static/js/containers/pages/CheckoutPage.js
Labels: Needs Review

#1897 Sorting pages in CMS admin by title - #171
  cms/wagtail_hooks.py
Labels: Waiting on Author

#1894 asadiqbal08/Do not show user past dates option for course runs.
  static/js/components/input/ProductSelector.js
  static/js/components/input/ProductSelector_test.js
  static/js/factories/ecommerce.js
Labels: Waiting on Author

#1785 Updated instructions for Programs, Program Runs, Courses, and Course …
  courses/README.md
Labels: Needs Review

#1902 fix email change confirmation
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
Labels: Waiting on Author

#1900 change b2b order coupon name
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
Labels: Waiting on Author

#1904 pad short username
  authentication/api.py
Labels: Waiting on Author

#1914 asadiqbal08/Addressing Sam's Feedback
  cms/templates/product_page.html
  static/js/containers/pages/CheckoutPage.js
Labels: Waiting on Author

#1915 asadiqbal08/mitxpro Updated the terms & condition text and link url
  mail/templates/b2b_receipt/body.html
  static/js/components/forms/B2BPurchaseForm.js
Labels: Waiting on Author

#1923 B2B/Bulk: Update coupon payment name to fix name collisions
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
Labels: Waiting on Author

#1918 Updated file watch renewal command to allow renewal of all sheets
  sheets/constants.py
  sheets/management/commands/setup_file_watch.py
Labels: Waiting on Author

#1916 Home page performance tweaks - #1908
  cms/templates/partials/image-carousel.html
  mitxpro/templates/base.html
Labels: Waiting on Author

#1926 Fix Order.MultipleObjectsReturned create_enrollment command
  courses/management/commands/create_enrollment.py
Labels: Waiting on Author

#1933 Fixed bug where coupon assignment sheets didn't have local DB record
  sheets/coupon_request_api.py
  sheets/coupon_request_api_test.py
Labels: Small Change, Waiting on Author
