Repository mitodl/mitxpro, pull requests merged in 2020-01, with the labels that each got.

#1452 asadiqbal08/mitxpro-1436 Fix coupon success message
  static/js/components/forms/CheckoutForm.js
Labels: Needs Review

#1454 Set coupon assignment sheet cells to protected
  sheets/api.py
  sheets/utils.py
Labels: Waiting on Author

#1443 Added batch Drive file sharing
  sheets/api.py
  sheets/api_test.py
  sheets/conftest.py
  sheets/exceptions.py
  sheets/utils.py
  sheets/utils_test.py
  sheets/views_test.py
Labels: Waiting on Author

#1453 #1398 Remove login/register from bulk purchase pages
  mitxpro/templates/base.html
  mitxpro/templatetags/latest_notification.py
  mitxpro/templatetags/startswith.py
  static/js/components/Header.js
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/js/containers/App.js
  static/js/containers/HeaderApp.js
Labels: Waiting on Author

#1450 #1418 Fix course run sync from edX
  app.json
  courses/utils.py
  mitxpro/settings.py
  requirements.in
  requirements.txt
Labels: Blocked, Waiting on Author

#1469 upgrade autoprefixer to fix builds
  package.json
  yarn.lock
Labels: Waiting on Author

#1459 Changed default renewal period for Drive webhooks to 12hrs
  mitxpro/settings.py
Labels: Waiting on Author

#1430 mitxpro-1393 Add contract number to b2b order
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
  b2b_ecommerce/factories.py
  b2b_ecommerce/migrations/0005_b2border_contract_number.py
  b2b_ecommerce/models.py
  b2b_ecommerce/views.py
  b2b_ecommerce/views_test.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/templates/b2b_receipt/body.html
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/forms/B2BPurchaseForm_test.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#1471 asadiqbal08/mitxpro-Introduce some more fields in address line
  authentication/pipeline/compliance.py
Labels: Waiting on Author

#1457 Fixed sheets app log message interpolation
  sheets/api.py
  sheets/views.py
Labels: Waiting on Author

#1486 Pinned the version for freezegun
  test_requirements.txt
Labels: Waiting on Author

#1473 Added retry for timed-out Mailgun API requests
  mitxpro/utils.py
  mitxpro/utils_test.py
  sheets/constants.py
  sheets/mail_api.py
Labels: Waiting on Author

#1470 #1385 Management command to create enrollment in closed course
  courses/management/commands/create_enrollment.py
  courses/serializers.py
Labels: Waiting on Author

#1490 Removed 'get_embed' Wagtail library function tests
  cms/embeds_test.py
Labels: Waiting on Author

#1484 Allowed multiple coupon requests with same contract number
  sheets/admin.py
  sheets/api.py
  sheets/api_test.py
  sheets/factories.py
  sheets/management/commands/create_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_requests.py
  sheets/management/utils.py
  sheets/migrations/0007_fill_in_gen_request_date_completed.py
  sheets/migrations/0009_add_gen_request_coupon_name.py
  sheets/migrations/0010_fill_in_gen_request_coupon_name.py
  sheets/migrations/0011_gen_request_coupon_name_index.py
  sheets/models.py
  sheets/utils.py
Labels: Waiting on Author

#1482 Fixed coupon redemption handling to account for non-spreadsheet bulk enrollments
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#1478 Streamlined failed HTTP response messaging
  courseware/api.py
  courseware/api_test.py
  courseware/exceptions.py
  courseware/management/commands/repair_missing_courseware_records.py
  ecommerce/api_test.py
  mitxpro/test_utils.py
  mitxpro/test_utils_test.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  users/utils.py
Labels: Waiting on Author

#1489 Split sheets app code
  sheets/api.py
  sheets/api_test.py
  sheets/constants.py
  sheets/coupon_assign_api.py
  sheets/coupon_request_api.py
  sheets/coupon_request_api_test.py
  sheets/management/commands/create_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/process_coupon_requests.py
  sheets/management/commands/update_assignment_message_statuses.py
  sheets/management/utils.py
  sheets/tasks.py
  sheets/tasks_test.py
  sheets/views.py
Labels: Waiting on Author

#1494 Fixed off-by-one error with coupon assignment sheet enrolled status
  sheets/tasks.py
Labels: Waiting on Author

#1472 Allow product_id and CouponCode to be specificed in URL
  static/images/mitlogo.png
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/forms/B2BPurchaseForm_test.js
  static/js/components/input/ProductSelector.js
  static/js/components/input/ProductSelector_test.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/factories/ecommerce.js
Labels: Waiting on Author

#1497 #1277 Static content (JS) via Webpack for Django
  cms/templates/catalog_page.html
  cms/templates/home_page.html
  cms/templates/product_page.html
  mitxpro/templates/base.html
  mitxpro/views_test.py
  package.json
  static/js/courseware_carousel.js
  static/js/entry/django.js
  static/js/entry/third-party.js
  static/js/faculty_carousel.js
  static/js/image_carousel.js
  static/js/testimonials_carousel.js
  webpack.config.shared.js
  yarn.lock
Labels: Waiting on Author

#1504 handlebars plus django version update
  package.json
  requirements.txt
  yarn.lock
Labels: Waiting on Author

#1499 Add error logging for program orders with no run selections
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#1503 Added refund processing via Google Sheets
  app.json
  courses/api.py
  courses/constants.py
  courses/management/commands/defer_enrollment.py
  courses/management/commands/refund_enrollment.py
  courses/management/commands/transfer_enrollment.py
  courses/management/utils.py
  courses/models.py
  courses/utils.py
  mitxpro/settings.py
  mitxpro/utils.py
  mitxpro/utils_test.py
  sheets/admin.py
  sheets/api.py
  sheets/conftest.py
  sheets/constants.py
  sheets/coupon_assign_api.py
  sheets/coupon_request_api.py
  sheets/coupon_request_api_test.py
  sheets/management/commands/process_refund_requests.py
  sheets/management/commands/setup_file_watch.py
  sheets/management/utils.py
  sheets/migrations/0012_refundrequest.py
  sheets/models.py
  sheets/refund_request_api.py
  sheets/tasks.py
  sheets/urls.py
  sheets/utils.py
  sheets/utils_test.py
  sheets/views.py
  sheets/views_test.py
Labels: Waiting on Author
