Repository mitodl/mitxpro, pull requests merged in 2020-02, with the labels that each got.

#1509 Add CEU override for certificates
  cms/blocks.py
  cms/forms.py
  cms/migrations/0045_certificate_page_courserun_overrides.py
  cms/models.py
  cms/templates/certificate_page.html
  courses/models.py
Labels: Needs Review

#1498 Allow email change #369
  app.json
  courseware/api.py
  mail/constants.py
  mail/templates/change_email/body.html
  mail/templates/change_email/body.txt
  mail/templates/change_email/subject.txt
  mail/verification_api.py
  mitxpro/serializers.py
  mitxpro/serializers_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  static/js/components/forms/ChangePasswordForm.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/settings/AccountSettingsPage.js
  static/js/containers/pages/settings/AccountSettingsPage_test.js
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/scss/common.scss
  users/migrations/0012_changeemailrequest.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Needs Review

#1512 Sticky Enroll Button Changes
  cms/templates/partials/enroll_button.html
  cms/templates/partials/hero.html
  cms/templates/partials/subnav.html
  static/scss/detail/subnav.scss
Labels: Waiting on Author

#1518 Fixed bug with column definition for refund request sheet
  sheets/utils.py
Labels: Small Change, Waiting on Author

#1517 Fixed unenrollment email start date text
  mail/templates/course_run_unenrollment/body.html
Labels: Small Change, Waiting on Author

#1505 asadiqbal08/mitxpro Added Enterprise Privacy Statement + UI Updates
  static/js/components/B2BCheckoutExplanation.js
  static/js/components/forms/B2BPurchaseForm.js
  static/js/components/input/ProductSelector.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/scss/checkout.scss
Labels: Waiting on Author

#1521 asadiqbal08/Added live check while filtering runs
  courses/tasks.py
Labels: Waiting on Author

#1525 asadiqbal08/Added title for resource pages
  mitxpro/templates/resource_template.html
Labels: Needs Review

#1526 Fix Course Certificate CEUs Override
  cms/forms.py
Labels: Waiting on Author

#1528 Revert "allow email change"
  app.json
  courseware/api.py
  mail/constants.py
  mail/templates/change_email/body.html
  mail/templates/change_email/body.txt
  mail/templates/change_email/subject.txt
  mail/verification_api.py
  mitxpro/serializers.py
  mitxpro/serializers_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  static/js/components/forms/ChangePasswordForm.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/settings/AccountSettingsPage.js
  static/js/containers/pages/settings/AccountSettingsPage_test.js
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/scss/common.scss
  users/migrations/0012_changeemailrequest.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Needs Review

#1522 Fixed incorrect sheets module reference in tasks
  sheets/tasks.py
Labels: Needs Review, Small Change

#1510 Pass readable product id to checkout page in URL
  ecommerce/api.py
  ecommerce/serializers.py
  ecommerce/views_test.py
  static/js/components/forms/CheckoutForm.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#1532 Make Account Settings page private
  static/js/containers/App.js
Labels: Waiting on Author

#1531 asadiqbal08/Fix video on catalog page is wrapping to a new line.
  cms/templates/partials/hero.html
Labels: Waiting on Author

#1524 Remove unused CourseCatalogView
  courses/views.py
Labels: Small Change, Waiting on Author

#1514 Handle deferrals via Google Sheets
  app.json
  courses/admin.py
  courses/api.py
  courses/api_test.py
  courses/management/commands/create_enrollment.py
  courses/management/commands/defer_enrollment.py
  courses/management/utils.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/utils.py
  mitxpro/settings.py
  sheets/admin.py
  sheets/constants.py
  sheets/coupon_request_api_test.py
  sheets/deferral_request_api.py
  sheets/enrollment_change_api.py
  sheets/management/commands/process_deferral_requests.py
  sheets/management/commands/process_refund_requests.py
  sheets/migrations/0013_deferralrequest.py
  sheets/models.py
  sheets/refund_request_api.py
  sheets/utils.py
Labels: Waiting on Author

#1537 Load products on coupon page with visible_in_bulk_form=false
  ecommerce/serializers.py
  ecommerce/views.py
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#1536 asadiqbal08/fix currency should have two decimal places
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
Labels: Waiting on Author

#1535 #369 allow email change
  app.json
  courseware/api.py
  mail/constants.py
  mail/templates/change_email/body.html
  mail/templates/change_email/body.txt
  mail/templates/change_email/subject.txt
  mail/verification_api.py
  mitxpro/serializers.py
  mitxpro/serializers_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  static/js/components/forms/ChangePasswordForm.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/settings/AccountSettingsPage.js
  static/js/containers/pages/settings/AccountSettingsPage_test.js
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/scss/common.scss
  users/migrations/0012_changeemailrequest.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Waiting on Author

#1540 Revert "Merge pull request #1535 from mitodl/umar/369-allow-email-cha…
  app.json
  courseware/api.py
  mail/constants.py
  mail/templates/change_email/body.html
  mail/templates/change_email/body.txt
  mail/templates/change_email/subject.txt
  mail/verification_api.py
  mitxpro/serializers.py
  mitxpro/serializers_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  static/js/components/forms/ChangePasswordForm.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/settings/AccountSettingsPage.js
  static/js/containers/pages/settings/AccountSettingsPage_test.js
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/scss/common.scss
  users/migrations/0012_changeemailrequest.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Needs Review

#1539 asadiqbal08/mitxpro: Users with bad edX auth can complete orders
  courses/api.py
  courses/management/utils.py
Labels: Waiting on Author

#1530 Fixed flaky bulk enrollment list test
  ecommerce/views_test.py
Labels: Small Change, Waiting on Author

#1515 course run on program checkout page
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/lib/util.js
Labels: Waiting on Author

#1542 Change Street Address label (Home or Residential)
  static/js/components/forms/ProfileFormFields.js
Labels: Waiting on Author

#1546 #59 Fix unused coupon banner bug after command create enrollment
  courses/management/commands/create_enrollment.py
Labels: Waiting on Author

#1551 Upgrade postgres version in docker-compose, and update to Python 3.7
  Dockerfile
  docker-compose.yml
  hubspot/conftest.py
Labels: Small Change, Waiting on Author

#1552 Django admin improvements
  courses/admin.py
  ecommerce/admin.py
  ecommerce/models.py
Labels: Waiting on Author

#1556 Removed course run preselect logic in checkout
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
Labels: Waiting on Author

#1550 Added deferral sheet file watch and management command
  sheets/management/commands/setup_file_watch.py
  sheets/tasks.py
  sheets/views.py
Labels: Waiting on Author

#1554 Update heroku to Python 3.7
  runtime.txt
Labels: Waiting on Author

#1538 Web app should issue appropriate headers for cache management
  config/nginx.conf.erb
Labels: Waiting on Author

#1563 add readable_id in search fields in course admin
  courses/admin.py
Labels: Waiting on Author

#1562 Actually fixed enrollment change sheet file watch renewal
  sheets/api.py
  sheets/constants.py
  sheets/enrollment_change_api.py
  sheets/management/commands/setup_file_watch.py
  sheets/utils.py
  sheets/views.py
Labels: Needs Review

#1564 asadiqbal08/mitxpro- Fix Checkout page crashes if user has inactive enrollment code
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Waiting on Author

#1544 Added program runs concept and tracking of program run purchases
  courses/admin.py
  courses/constants.py
  courses/factories.py
  courses/migrations/0024_programrun.py
  courses/models.py
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0025_add_programrun_models.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views_test.py
  sheets/conftest.py
  sheets/coupon_request_api.py
  sheets/coupon_request_api_test.py
Labels: Waiting on Author

#1543 Revert "Revert 'Allow Email Change, PR#1535'"
  app.json
  courseware/api.py
  courseware/api_test.py
  courseware/tasks.py
  courseware/tasks_test.py
  mail/constants.py
  mail/templates/change_email/body.html
  mail/templates/change_email/body.txt
  mail/templates/change_email/subject.txt
  mail/verification_api.py
  mail/verification_api_test.py
  mitxpro/settings.py
  mitxpro/urls.py
  static/js/components/forms/ChangePasswordForm.js
  static/js/components/forms/ChangePasswordForm_test.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/pages/settings/AccountSettingsPage.js
  static/js/containers/pages/settings/AccountSettingsPage_test.js
  static/js/containers/pages/settings/EmailConfirmPage.js
  static/js/containers/pages/settings/EmailConfirmPage_test.js
  static/js/flow/authTypes.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/scss/common.scss
  users/factories.py
  users/migrations/0012_changeemailrequest.py
  users/models.py
  users/serializers.py
  users/serializers_test.py
  users/urls.py
  users/views.py
  users/views_test.py
Labels: Waiting on Author

#1533 API v1 routes
  courses/urls.py
  courses/views/__init__.py
  courses/views/v1/__init__.py
  courses/views_test.py
Labels: Waiting on Author
