Repository mitodl/mitxpro, pull requests merged in 2020-06, with the labels that each got.

#1792 Changed pytest mocker usages to stop using context processors
  compliance/api_test.py
  scripts/test/js_test.sh
Labels: Small Change, Waiting on Author

#1790 Removed index/unique constraint google file watch expiration field
  sheets/migrations/0016_remove_file_watch_expiration_idx.py
  sheets/models.py
Labels: Needs Review, Small Change

#1789 Fix Broken Image
  ecommerce/models.py
Labels: Waiting on Author
