Repository mitodl/mitxpro, pull requests merged in 2020-10, with the labels that each got.

#1927 product page performance tweaks
  mitxpro/templates/base.html
  mitxpro/templates/footer.html
  static/scss/icomoon.scss
Labels: Waiting on Author

#1930 Added courses list ordering for B2B Bulk order page
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1938 Improved BulkCouponAssignment admin to be searchable and show timestamps
  ecommerce/admin.py
Labels: Small Change, Waiting on Author

#1949 Added info about setting up Open edX user and token
  docs/configure_open_edx.md
Labels: DevOps, Needs Review

#1936 xPRO Catalog page performance improvements
  cms/models.py
Labels: Waiting on Author

#1948 Fixed copyright year text and made it dynamic
  mail/templates/b2b_receipt/body.html
  mitxpro/templates/footer.html
  static/js/containers/pages/ReceiptPage.js
Labels: Waiting on Author

#1935 B2b Bulk Course/Program dates
  ecommerce/serializers.py
  ecommerce/views.py
  ecommerce/views_test.py
  static/js/components/input/ProductSelector.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#1947 Associate order with Course Enrollment in enrollment command
  courses/management/commands/create_enrollment.py
Labels: Waiting on Author

#1943 Dependabot alert: Upgraded yargs-parser above 13.1.2
  package.json
  yarn.lock
Labels: Waiting on Author

#1955 fix kind-of security alert
  package.json
  yarn.lock
Labels: Waiting on Author

#1953 fix minimist security alert
  package.json
  yarn.lock
Labels: Waiting on Author

#1957 fix icomoon svg broken icons
  mitxpro/templates/base.html
  static/scss/icomoon.scss
  static/scss/slick.scss
Labels: Waiting on Author

#1954 prioritize contract_number to be used as payment_transaction
  b2b_ecommerce/api.py
  b2b_ecommerce/api_test.py
Labels: Waiting on Author

#1958 Synced xpro user name change with edX
  courseware/api.py
  courseware/api_test.py
  courseware/constants.py
  courseware/exceptions.py
  courseware/tasks.py
  courseware/tasks_test.py
  users/views.py
  users/views_test.py
Labels: Waiting on Author

#1970 Added support for affiliate links
  affiliate/README.md
  affiliate/__init__.py
  affiliate/admin.py
  affiliate/api.py
  affiliate/api_test.py
  affiliate/apps.py
  affiliate/constants.py
  affiliate/factories.py
  affiliate/middleware.py
  affiliate/middleware_test.py
  affiliate/migrations/0001_affiliate_initial_models.py
  affiliate/migrations/__init__.py
  affiliate/models.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/models.py
  ecommerce/views.py
  ecommerce/views_test.py
  mail/verification_api.py
  mail/verification_api_test.py
  mitxpro/settings.py
  static/js/containers/pages/register/RegisterConfirmPage.js
  static/js/lib/queries/auth.js
  users/models.py
  users/models_test.py
  users/serializers.py
  users/serializers_test.py
Labels: Waiting on Author

#1952 Improved task execution and added tracking for sheets file watch renewal
  mitxpro/settings.py
  requirements.txt
  sheets/admin.py
  sheets/api.py
  sheets/constants.py
  sheets/migrations/0017_filewatchrenewalattempt.py
  sheets/models.py
  sheets/tasks.py
Labels: Waiting on Author
