Repository mitodl/mitxpro, pull requests merged in 2020-04, with the labels that each got.

#1619 B2B Bulk Receipt UI Updates for Email
  b2b_ecommerce/admin.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/templates/b2b_receipt/body.html
Labels: Waiting on Author

#1620 Added support for ignored rows in a coupon request spreadsheet
  sheets/conftest.py
  sheets/coupon_request_api.py
  sheets/utils.py
Labels: Small Change, Waiting on Author

#1625 Used dynamic image loading for select CMS pages
  cms/templates/certificate_page.html
  cms/templates/partials/faculty-carousel.html
  cms/templates/partials/image-carousel.html
  cms/templates/partials/learning-techniques.html
  cms/templates/partials/testimonial-carousel.html
  courses/models.py
  mitxpro/urls.py
  static/js/containers/pages/ReceiptPage.js
Labels: Waiting on Author

#1631 Pillow upgrade - #132
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1616 Improve uWSGI configuration
  uwsgi.ini
Labels: Waiting on Author

#1634 Various admin fixes + timestamped model admin class
  b2b_ecommerce/migrations/0006_b2border_admin_fix.py
  b2b_ecommerce/models.py
  courses/admin.py
  ecommerce/admin.py
  mitxpro/admin.py
  users/admin.py
Labels: Waiting on Author

#1633 Program certificate fix for missing enrollment - #126
  courses/utils.py
Labels: Waiting on Author

#1635 Added field to track when file watch requests come in
  sheets/admin.py
  sheets/migrations/0015_googlefilewatch_last_request_received.py
  sheets/models.py
  sheets/views.py
Labels: Waiting on Author

#1640 Fixed Receipt admin class
  ecommerce/admin.py
Labels: Small Change, Waiting on Author

#1636 Bulk purchase text updates - #136
  static/js/components/forms/B2BPurchaseForm.js
Labels: Waiting on Author

#1638 Don't display courses that have ended in Boeing voucher upload
  courses/models.py
  voucher/utils.py
Labels: Waiting on Author

#1646 remove users from the dataconsentagreement admin page
  ecommerce/admin.py
Labels: Waiting on Author

#1637 Bulk purchase form product alphabetic sorting - #137
  ecommerce/views.py
  ecommerce/views_test.py
  static/js/lib/queries/ecommerce.js
Labels: Waiting on Author

#1641 Remove py-call-osafterfork setting from uwsgi.ini
  uwsgi.ini
Labels: Waiting on Author

#1648 Added versioned image URL template tag to enable CMS image caching
  cms/templates/certificate_page.html
  cms/templates/partials/card_details_top.html
  cms/templates/partials/courseware-carousel-base.html
  cms/templates/partials/faculty-carousel.html
  cms/templates/partials/for-teams.html
  cms/templates/partials/hero.html
  cms/templates/partials/image-carousel.html
  cms/templates/partials/learning-techniques.html
  cms/templates/partials/target-audience.html
  cms/templates/partials/testimonial-carousel.html
  cms/templatetags/__init__.py
  cms/templatetags/image_version_url.py
  cms/templatetags/image_version_url_test.py
Labels: Waiting on Author

#1654 Moved test file for cms templatetags
  cms/template_tags_test.py
Labels: Waiting on Author

#1658 Move static/hash.txt rule before the generic static rule
  config/nginx.conf.erb
Labels: Waiting on Author

#1651 Update uWSGI to rename UWSGI_ env vars, remove redundant if-envs
  uwsgi.ini
Labels: Waiting on Author

#1642 acorn version bump
  .travis.yml
  Dockerfile-node
  package.json
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/containers/pages/ReceiptPage.js
  static/js/containers/pages/ReceiptPage_test.js
  static/js/containers/pages/admin/CreateCouponPage.js
  static/js/flow/authTypes.js
  static/js/flow/courseTypes.js
  static/js/flow/declarations.js
  static/js/flow/ecommerceTypes.js
  static/js/flow/reduxTypes.js
  static/js/flow/sinonTypes.js
  yarn.lock
Labels: Needs Review

#1656 Change URL routing to allow for program run ids
  cms/models.py
  cms/views_test.py
Labels: Needs Review

#1657 Fix product title/nested sorting on Product API - #146
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1750 change placement of order button on checkout page
  static/js/components/forms/CheckoutForm.js
Labels: Waiting on Author
