Repository mitodl/mitxpro, pull requests merged in 2020-03, with the labels that each got.

#1555 Sheets management utils tests
  sheets/management/utils_test.py
Labels: Waiting on Author

#1573 Integrated program runs for checkout
  cms/models.py
  courses/admin.py
  courses/constants.py
  courses/factories.py
  courses/management/commands/backfill_program_runs.py
  courses/migrations/0025_run_tag.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views_test.py
  localdev/seed/api.py
  localdev/seed/api_test.py
  localdev/seed/resources/seed_data.json
  localdev/seed/serializers.py
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/CheckoutPage_test.js
  static/js/factories/course.js
  static/js/factories/ecommerce.js
  static/js/flow/courseTypes.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/ecommerce.js
  static/js/lib/ecommerce_test.js
Labels: Waiting on Author

#1579 Fixed run_tag data migration
  courses/migrations/0025_run_tag.py
Labels: Small Change, Waiting on Author

#1575 Added RedBeat to handle task scheduling
  app.json
  docker-compose-notebook.yml
  docker-compose.yml
  mitxpro/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1581 Made email search case-insensitive for refunds/deferrals
  sheets/deferral_request_api.py
  sheets/refund_request_api.py
Labels: Small Change, Waiting on Author

#1569 Remove course run expiration dates #76
  courses/migrations/0026_nullify_expiration_date.py
  courses/models.py
Labels: Waiting on Author

#1583 add loading spinner to bulk purchase page
  static/js/containers/pages/CheckoutPage.js
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/lib/queries/ecommerce.js
  static/scss/checkout.scss
  static/scss/common.scss
Labels: Waiting on Author

#1582 Suppress system shutdown sentry errors
  mitxpro/sentry.py
  mitxpro/settings.py
Labels: Waiting on Author

#1574 apply coupons to all course runs of a course
  ecommerce/api.py
  ecommerce/conftest.py
  ecommerce/migrations/0026_coupon_include_future_runs.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/signals.py
  ecommerce/signals_test.py
  static/js/components/forms/CouponForm.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#1567 Optimizing N+1 ORM Bulk purchase operations
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
Labels: Waiting on Author

#1549 Global coupons/promos #62
  .vscode/settings.json
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/migrations/0027_coupon_code_is_global.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views_test.py
  static/js/components/forms/CouponForm.js
  static/js/components/forms/CouponForm_test.js
  static/js/flow/ecommerceTypes.js
  static/scss/ecommerce-admin.scss
Labels: Waiting on Author

#1589 set False as default in include_future_runs
  ecommerce/api.py
  ecommerce/conftest.py
  ecommerce/migrations/0028_include_future_runs_default.py
  ecommerce/models.py
  ecommerce/serializers_test.py
Labels: Waiting on Author

#1585 Added assignment sheet webhook
  app.json
  ecommerce/migrations/0027_bulk_assignment_date_fields.py
  ecommerce/models.py
  mitxpro/settings.py
  sheets/api.py
  sheets/conftest.py
  sheets/coupon_assign_api.py
  sheets/coupon_request_api.py
  sheets/management/commands/process_coupon_assignment_sheet.py
  sheets/management/commands/setup_file_watch.py
  sheets/migrations/0014_file_watch_for_assignment_sheets.py
  sheets/models.py
  sheets/tasks.py
  sheets/utils.py
  sheets/views.py
Labels: Waiting on Author

#1591 Fixed conflicting ecommerce migration file names
  ecommerce/migrations/0029_bulk_assignment_date_fields.py
Labels: Small Change, Waiting on Author

#1588 Bulk Purchase: change error message to an HREF instead of a MAILTO
  static/js/components/notifications/index.js
  static/js/components/notifications/index_test.js
  static/js/constants.js
  static/js/containers/pages/b2b/B2BReceiptPage.js
  static/js/containers/pages/b2b/B2BReceiptPage_test.js
  static/js/reducers/notifications.js
Labels: Needs Review

#1593 remove SHOW_UNREDEEMED_COUPON_ON_DASHBOARD feature flag
  app.json
  mitxpro/settings.py
  users/serializers.py
  users/views_test.py
Labels: Needs Review

#1597 Pin redis version to 5.0.5 in docker config
  docker-compose.yml
Labels: Waiting on Author

#1596 Pin nginx to 1.16.1 in docker config
  docker-compose.yml
Labels: Waiting on Author

#1595 Retire users by email address in addition to username
  users/management/commands/retire_users.py
  users/management/commands/retire_users_test.py
Labels: Waiting on Author

#1604 Choose future program run from catalog instead of active one
  cms/models.py
  cms/views_test.py
Labels: Needs Review

#1600 asadiqbal08/Change the text on the enrollment code email
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  mail/templates/bulk_enroll/body.html
Labels: Waiting on Author

#1606 Admin: on course and program certificates, show date created and updated
  courses/admin.py
Labels: Waiting on Author

#1605 upgrade wagtail to 2.7.1
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1612 Add a text-only link in password change email
  mail/templates/password_reset/body.html
Labels: Waiting on Author

#1611 asadiqbal08/Add a text-only link on verification emails
  mail/templates/verification/body.html
Labels: Waiting on Author

#1610 Fix tracking of course run selections when completing orders
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/factories.py
  ecommerce/migrations/0030_linerunselection.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views.py
  ecommerce/views_test.py
  mitxpro/test_utils.py
Labels: Waiting on Author

#1602 Choose an active course run when the current product is expired.
  ecommerce/serializers.py
  ecommerce/views_test.py
  static/js/containers/pages/CheckoutPage.js
Labels: Needs Review

#1601 asadiqbal08/Utilizing search param in zendesk help widget
  cms/templates/product_page.html
  mitxpro/settings.py
  mitxpro/views.py
  mitxpro/views_test.py
  package.json
  static/js/components/forms/CheckoutForm.js
  static/js/components/forms/CheckoutForm_test.js
  static/js/entry/root.js
  static/js/flow/declarations.js
  yarn.lock
Labels: Waiting on Author

#1592 Streamlined Wagtail configuration and seed data provisioning
  README.md
  cms/api.py
  cms/api_test.py
  cms/management/commands/configure_wagtail.py
  cms/management/commands/setup_index_pages.py
  cms/models.py
  cms/utils.py
  localdev/seed/api.py
Labels: Waiting on Author

#1622 Optimize performance(N+1 queries) on admin dataconsentagreement page
  ecommerce/admin.py
Labels: Needs Review

#1623 Fix user login for non-new, not yet activated users
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/views_test.py
Labels: Waiting on Author
