Repository mitodl/mitxpro, pull requests merged in 2022-09, with the labels that each got.

#2418 Vertically center the certificate when printing
  cms/templates/certificate_page.html
  static/scss/certificates/certificate.scss
Labels: Needs Review

#2421 display start and end date on certificate template
  cms/templates/certificate_page.html
Labels: Needs Review, Small Change

#2422 Certificate page should not be moved to Certificate Index Page child
  cms/api.py
Labels: Waiting on Author

#2427 xPro-2411 Fix search for data consent agreements admin
  ecommerce/admin.py
Labels: Waiting on Author

#2416 Versioning of certificate template
  cms/models.py
  courses/admin.py
  courses/migrations/0028_certificate_page_revision_for_course_and_program.py
  courses/models.py
Labels: Needs Review
