Repository mitodl/mitxpro, pull requests merged in 2023-10, with the labels that each got.

#2775 Fixing formatting errors on receipt page, should not charge tax if TaxRate
  ecommerce/api.py
  ecommerce/mail_api_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
Labels: Waiting on Author, product:xpro

#2779 tests: adds frontend tests for the taxes
  static/js/lib/ecommerce_test.js
Labels: Needs Review

#2780 Adds indexes to the netblock table
  maxmind/migrations/0002_add_indexes_to_decimal_ips.py
  maxmind/models.py
Labels: Waiting on Author, product:xpro

#2786 fix: make `platform` a required field for Courses/Programs
  courses/admin.py
  courses/factories.py
  courses/migrations/0037_make_platform_non_nullable.py
  courses/models.py
  courses/models_test.py
  courses/serializers_test.py
  localdev/seed/api.py
  yarn.lock
Labels: Waiting on Author

#2790 feat: display tax rate on checkout, receipt and email
  mail/templates/product_order_receipt/body.html
  static/js/components/forms/CheckoutForm.js
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/ReceiptPage.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/ecommerce.js
  static/js/lib/ecommerce_test.js
  yarn.lock
Labels: Waiting on Author

#2792 fix: platform name search in Django Admin Courses/Programs
  courses/admin.py
Labels: Waiting on Author

#2747 fix: configure course or program format
  cms/constants.py
  cms/migrations/0064_productpage_format_field.py
  cms/models.py
  cms/models_test.py
  cms/templates/partials/metadata-tiles.html
  courses/serializers.py
  courses/serializers_test.py
  localdev/seed/resources/seed_data.json
Labels: Waiting on Author

#2794 fix: display discount amount as negative
  mail/templates/product_order_receipt/body.html
  mail/templatetags/format_discount.py
  mail/templatetags/format_discount_test.py
  static/js/components/forms/CheckoutForm.js
  static/js/components/forms/CheckoutForm_test.js
  static/js/containers/pages/ReceiptPage.js
  static/js/lib/ecommerce.js
  static/js/lib/ecommerce_test.js
Labels: Waiting on Author

#2799 fix: receipt email typo
  mail/templates/b2b_receipt/body.html
  mail/templates/product_order_receipt/body.html
Labels: Waiting on Author

#2801 feat: add xpro catalog link when no courseware is associated
  cms/templates/webinar_page.html
Labels: Waiting on Author
