Repository mitodl/mitxpro, pull requests merged in 2023-09, with the labels that each got.

#2716 refactor!: rename visible_in_bulk_form to is_private in product model
  ecommerce/migrations/0038_rename_visible_in_bulk_form_product_is_private.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views_test.py
  static/js/containers/pages/b2b/B2BPurchasePage.js
  static/js/containers/pages/b2b/B2BPurchasePage_test.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
Labels: Waiting on Author

#2724 fix: update hubspot settings default values
  mitxpro/settings.py
Labels: Waiting on Author

#2715 feat: Use poetry instead of requirements files
  .github/workflows/ci.yml
  Dockerfile
  README.md
  app.base.json
  app.json
  authentication/views.py
  authentication/views_test.py
  cms/factories.py
  cms/models.py
  cms/models_test.py
  courses/admin.py
  courses/api_test.py
  courses/models.py
  courses/serializers.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/conftest.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  fixtures/common.py
  hubspot_xpro/conftest.py
  hubspot_xpro/serializers.py
  hubspot_xpro/serializers_test.py
  mitxpro/templatetags/latest_notification.py
  mitxpro/test_utils.py
  mitxpro/test_utils_test.py
  poetry.lock
  pylintrc
  pyproject.toml
  pytest.ini
  requirements.in
  requirements.txt
  runtime.txt
  scripts/test/detect_missing_migrations.sh
  scripts/test/python_tests.sh
  test_requirements.txt
  users/management/commands/retire_users.py
  users/migrations/0005_profile.py
  users/models.py
  users/serializers.py
  users/serializers_test.py
  users/utils_test.py
  voucher/utils_test.py
  voucher/views_test.py
Labels: Waiting on Author

#2763 feat: force all enrollments
  courses/api.py
  courses/api_test.py
  courseware/api.py
  courseware/api_test.py
Labels: Waiting on Author

#2772 Adds tax rate calculation support
  .gitignore
  .vscode/settings.json
  app.json
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/factories.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/migrations/0039_add_tax_rate_table.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  ecommerce/views.py
  ecommerce/views_test.py
  mail/templatetags/calculate_tax.py
  mail/templatetags/calculate_tax_total.py
  maxmind/README.md
  maxmind/__init__.py
  maxmind/admin.py
  maxmind/api.py
  maxmind/api_test.py
  maxmind/apps.py
  maxmind/factories.py
  maxmind/management/__init__.py
  maxmind/management/commands/import_maxmind_data.py
  maxmind/migrations/0001_add_geoname_and_netblock_tables.py
  maxmind/migrations/__init__.py
  maxmind/models.py
  mitxpro/settings.py
  mitxpro/utils_test.py
Labels: Waiting on Author, product:xpro

#2773 feat: display tax in regular checkout
  ecommerce/mail_api_test.py
  ecommerce/migrations/0040_alter_taxrate_tax_rate.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/serializers_test.py
  mail/templates/product_order_receipt/body.html
  static/js/components/forms/CheckoutForm.js
  static/js/containers/pages/ReceiptPage.js
  static/js/factories/ecommerce.js
  static/js/flow/ecommerceTypes.js
  static/js/lib/ecommerce.js
  static/scss/checkout.scss
Labels: Needs Review
