Repository mitodl/mitxpro, pull requests merged in 2024-12, with the labels that each got.

#3329 feat: add emeritus api list view
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
Labels: Waiting on Author

#3327 chore: change backend name
  app.json
  courseware/api.py
  courseware/api_test.py
  docs/configure_open_edx.md
  mitxpro/management/commands/configure_instance.py
  mitxpro/settings.py
Labels: Waiting on Author, On Hold

#3330 feat: add Global Alumni in external course sync
  .env.example
  .github/workflows/ci.yml
  app.json
  courses/management/commands/sync_external_course_runs.py
  courses/migrations/0041_platform_sync_daily.py
  courses/models.py
  courses/models_test.py
  courses/sync_external_courses/external_course_sync_api.py
  courses/sync_external_courses/external_course_sync_api_client.py
  courses/sync_external_courses/external_course_sync_api_client_test.py
  courses/sync_external_courses/external_course_sync_api_test.py
  courses/sync_external_courses/test_data/batch_test.json
  courses/tasks.py
  courses/tasks_test.py
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
  mitxpro/settings.py
Labels: Waiting on Author

#3324 feat: Course overview child page added
  cms/factories.py
  cms/migrations/0073_course_overview_page.py
  cms/models.py
  cms/models_test.py
  cms/templates/partials/course-overview.html
  cms/templates/partials/subnav.html
  cms/templates/product_page.html
  cms/views_test.py
  courses/sync_external_courses/external_course_sync_api.py
  static/scss/detail/course-overview.scss
  static/scss/layout.scss
Labels: Waiting on Author

#3318 feat: How you will learn and B2B section added for external courses
  cms/constants.py
  cms/factories.py
  cms/management/commands/create_common_child_page_for_external_courses.py
  cms/migrations/0074_common_component_pages.py
  cms/models.py
  cms/models_test.py
  cms/utils.py
  cms/utils_test.py
  cms/wagtail_hooks.py
  courses/sync_external_courses/external_course_sync_api.py
Labels: Waiting on Author

#3341 feat: make course searchable in courseRun admin
  courses/admin.py
Labels: Waiting on Author

#3336 min_weeks and max_weeks field added to replace duration field
  cms/migrations/0075_add_min_max_weeks.py
  cms/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/sync_external_courses/external_course_sync_api.py
  courses/sync_external_courses/external_course_sync_api_test.py
Labels: Waiting on Author

#3337 Add min and max weekly_hours to reflect time_commitment
  cms/migrations/0076_min_max_weekly_hours.py
  cms/models.py
  courses/serializers.py
  courses/serializers_test.py
Labels: Needs Review

#3343 fix: replace matchPackages with matchPackageNames
  renovate.json
Labels: Needs Review

#3351 fix: npm tests locally
  scripts/test/js_test.sh
Labels: Needs Review, Waiting on Author
